export const RECOMMENDED_TAGS = [
  // Blockchain & Web3
  "Blockchain",
  "Web3",
  "Ethereum",
  "Solidity",
  "Smart Contracts",
  "Ethers.js",
  "Web3.js",
  "Hardhat",
  "Foundry",
  "IPFS",
  "DeFi",
  "NFT",
  "Polygon",
  "MetaMask",

  // Rust & Solana
  "Rust",
  "Solana",

  // Databases
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Prisma",
  "SQL",
  "NoSQL",
  "Database Design",
  "ORM",
  "Supabase",
  "Firebase",

  // API & Auth
  "REST API",
  "GraphQL",
  "JWT",
  "Authentication",

  // Frontend
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Redux",
  "Tailwind CSS",
  "Framer Motion",
  "Vite",
  "SASS",
  "Material UI",
  "Responsive Design",
  "UI/UX",
  "js",

  // Mobile
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "Expo",
  "Android",
  "iOS",
  "Dart",
  "Mobile UI",
  "NativeWind",
  "Push Notifications",

  // Game Dev
  "Unity",
  "Unreal Engine",
  "C#",
  "C++",
  "Godot",
  "Game Physics",
  "Blender",
  "3D Modeling",
  "Game AI",
  "Multiplayer",
  "OpenGL",

  // AI & ML
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Neural Networks",
  "LLM",
  "OpenAI API",
  "Computer Vision",
  "NLP",
  "Data Analysis",
  "Scikit-learn",
  "Pandas",

  // Backend
  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "FastAPI",
  "Java",
  "Spring Boot",
  "RabbitMQ",
  "Microservices",

  // Testing
  "Testing",
  "Jest",
  "Vitest",
  "Cypress",
  "Playwright",
  "Selenium",
  "Unit Testing",
  "Integration Testing",
  "Automation Testing",
  "QA",
  "Bug Tracking",

  // DevOps
  "Docker",
  "Kubernetes",
  "CI/CD",
  "GitHub Actions",
  "Linux",
  "Nginx",
  "Terraform",
  "AWS",
  "Azure",
  "Monitoring",
  "Jenkins",
  "Ansible",

  // Data Science
  "Python",
  "NumPy",
  "Matplotlib",
  "Data Visualization",
  "Statistics",
  "Jupyter",
  "Big Data",
  "Data Analytics",

  // Security
  "Ethical Hacking",
  "Penetration Testing",
  "Network Security",
  "OWASP",
  "Kali Linux",
  "Cryptography",
  "Cyber Defense",
  "Web Security",
  "Reverse Engineering",

  // Cloud
  "Google Cloud",
  "Cloud Functions",
  "Serverless",
  "Cloud Security",
  "Vercel",
  "Netlify",

  // Quantum
  "Quantum Mechanics",
  "Qiskit",
  "Quantum Algorithms",
  "Quantum Circuits",
  "Qubits",
  "IBM Quantum",
  "Quantum Programming",
];
export const CATEGORIES = [
  "Blockchain Development",
  "Full Stack Development",
  "Frontend Development",
  "Mobile Development",
  "Game Development",
  "ML & AI",
  "Backend Development",
  "Quality Assurance",
  "DevOps",
  "Data Science",
  "Cybersecurity",
  "Cloud Computing",
  "Database Management",
  "Quantum Computing",
];

export const DIFFICULTIES = ["Beginner", "Intermediate", "Advanced"];
