export const TRACKS = {
  fullstack: [
    {
      id: "mern",
      title: "MERN Developer",
      available: true,
      techs: ["MongoDB", "Express.js", "React", "Node.js"],
    },
    {
      id: "pern",
      title: "PERN Developer",
      available: true,
      techs: ["PostgreSQL", "Express.js", "React", "Node.js"],
    },
    {
      id: "t3",
      title: "T3 Stack Dev",
      available: true,
      techs: ["Next.js", "TypeScript", "Tailwind", "tRPC", "Prisma"],
    },
    {
      id: "fullstack-engineer",
      title: "Full Stack Engineer",
      available: true,
      techs: ["React", "Node.js", "SQL", "Docker"],
    },
    {
      id: "mean",
      title: "MEAN Developer",
      available: true,
      techs: ["MongoDB", "Express.js", "Angular", "Node.js"],
    },
    {
      id: "jamstack",
      title: "JAMstack Developer",
      available: true,
      techs: ["Next.js", "Gatsby", "Netlify", "Contentful"],
    },
    {
      id: "django-react",
      title: "Django + React Dev",
      available: true,
      techs: ["Python", "Django", "React", "PostgreSQL"],
    },
    {
      id: "rails-dev",
      title: "Ruby on Rails Dev",
      available: true,
      techs: ["Ruby", "Rails", "PostgreSQL", "Hotwire"],
    },
    {
      id: "next-fullstack",
      title: "Next.js Full Stack Dev",
      available: true,
      techs: ["Next.js", "TypeScript", "Prisma", "Vercel"],
    },
    {
      id: "laravel-vue",
      title: "Laravel + Vue Dev",
      available: false,
      techs: ["PHP", "Laravel", "Vue 3", "MySQL"],
    },
    {
      id: "sveltekit-dev",
      title: "SvelteKit Developer",
      available: true,
      techs: ["Svelte", "SvelteKit", "TypeScript", "Vite"],
    },
    {
      id: "nuxt-dev",
      title: "Nuxt Developer",
      available: true,
      techs: ["Vue", "Nuxt", "TypeScript", "Nitro"],
    },
    {
      id: "astro-dev",
      title: "Astro Developer",
      available: true,
      techs: ["Astro", "Islands", "MDX", "TypeScript"],
    },
    {
      id: "remix-dev",
      title: "Remix Developer",
      available: false,
      techs: ["Remix", "React", "TypeScript", "Vite"],
    },
  ],
  backend: [
    {
      id: "api-dev",
      title: "API Developer",
      available: true,
      techs: ["Node.js", "Express.js", "REST", "Postman"],
    },
    {
      id: "db-engineer",
      title: "DB Engineer",
      available: true,
      techs: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
    },
    {
      id: "systems-dev",
      title: "Systems Dev",
      available: true,
      techs: ["Rust", "C++", "Go", "Linux"],
    },
    {
      id: "security-dev",
      title: "Security Dev",
      available: true,
      techs: ["OAuth", "JWT", "OWASP", "Cryptography"],
    },
    {
      id: "graphql-dev",
      title: "GraphQL Developer",
      available: true,
      techs: ["GraphQL", "Apollo", "Node.js", "Prisma"],
    },
    {
      id: "microservices",
      title: "Microservices Engineer",
      available: true,
      techs: ["Docker", "Kubernetes", "RabbitMQ", "gRPC"],
    },
    {
      id: "go-dev",
      title: "Go Developer",
      available: true,
      techs: ["Go", "Gin", "PostgreSQL", "Docker"],
    },
    {
      id: "rust-dev",
      title: "Rust Developer",
      available: true,
      techs: ["Rust", "Actix", "WebAssembly", "Tokio"],
    },
    {
      id: "java-spring",
      title: "Java Spring Dev",
      available: true,
      techs: ["Java", "Spring Boot", "Maven", "Hibernate"],
    },
    {
      id: "python-backend",
      title: "Python Backend Dev",
      available: true,
      techs: ["Python", "FastAPI", "SQLAlchemy", "Celery"],
    },
    {
      id: "grpc-dev",
      title: "gRPC Engineer",
      available: true,
      techs: ["gRPC", "Protobuf", "Go", "Node.js"],
    },
    {
      id: "node-dev",
      title: "Node.js Developer",
      available: false,
      techs: ["Node.js", "TypeScript", "Fastify", "Prisma"],
    },
  ],
  mobile: [
    {
      id: "react-native",
      title: "React Native Dev",
      available: true,
      techs: ["React Native", "JavaScript", "Expo", "Redux"],
    },
    {
      id: "flutter",
      title: "Flutter Dev",
      available: true,
      techs: ["Flutter", "Dart", "Firebase", "Riverpod"],
    },
    {
      id: "ios",
      title: "iOS Dev",
      available: true,
      techs: ["Swift", "SwiftUI", "Xcode", "CoreData"],
    },
    {
      id: "android",
      title: "Android Dev",
      available: true,
      techs: ["Kotlin", "Jetpack Compose", "Android Studio", "Room"],
    },
    {
      id: "kotlin-dev",
      title: "Kotlin Developer",
      available: true,
      techs: ["Kotlin", "Coroutines", "Ktor", "Gradle"],
    },
    {
      id: "swift-dev",
      title: "Swift Developer",
      available: true,
      techs: ["Swift", "SwiftUI", "Combine", "Xcode"],
    },
    {
      id: "maui",
      title: ".NET MAUI Dev",
      available: true,
      techs: ["C#", ".NET MAUI", "XAML", "Azure"],
    },
    {
      id: "pwa-dev",
      title: "PWA Developer",
      available: true,
      techs: ["JavaScript", "Service Workers", "Web APIs", "Lighthouse"],
    },
    {
      id: "ionic",
      title: "Ionic Developer",
      available: false,
      techs: ["Ionic", "Angular", "Capacitor", "TypeScript"],
    },
  ],
  aiml: [
    {
      id: "ml-engineer",
      title: "ML Engineer",
      available: true,
      techs: ["Python", "TensorFlow", "PyTorch", "Scikit-learn"],
    },
    {
      id: "data-scientist",
      title: "Data Scientist",
      available: true,
      techs: ["Python", "Pandas", "NumPy", "Matplotlib"],
    },
    {
      id: "ai-developer",
      title: "AI Developer",
      available: true,
      techs: ["Python", "LangChain", "OpenAI API", "FastAPI"],
    },
    {
      id: "nlp-engineer",
      title: "NLP Engineer",
      available: true,
      techs: ["Python", "HuggingFace", "spaCy", "NLTK"],
    },
    {
      id: "cv-engineer",
      title: "Computer Vision Engineer",
      available: true,
      techs: ["Python", "OpenCV", "YOLO", "PyTorch"],
    },
    {
      id: "llm-engineer",
      title: "LLM Engineer",
      available: true,
      techs: ["Python", "LangChain", "LlamaIndex", "Vector DBs"],
    },
    {
      id: "mlops",
      title: "MLOps Engineer",
      available: true,
      techs: ["MLflow", "Kubeflow", "Docker", "Airflow"],
    },
    {
      id: "data-engineer",
      title: "Data Engineer",
      available: true,
      techs: ["Spark", "Kafka", "Airflow", "dbt"],
    },
    {
      id: "rl-engineer",
      title: "Reinforcement Learning Engineer",
      available: true,
      techs: ["Python", "OpenAI Gym", "Ray RLlib", "PyTorch"],
    },
    {
      id: "prompt-engineer",
      title: "Prompt Engineer",
      available: false,
      techs: ["LLMs", "LangChain", "Python", "RAG"],
    },
  ],
  devops: [
    {
      id: "cloud",
      title: "Cloud Engineer",
      available: true,
      techs: ["AWS", "Terraform", "Docker", "Linux"],
    },
    {
      id: "cicd",
      title: "CI/CD Engineer",
      available: true,
      techs: ["GitHub Actions", "Jenkins", "ArgoCD", "CircleCI"],
    },
    {
      id: "sre",
      title: "Site Reliability Engineer",
      available: true,
      techs: ["Prometheus", "Grafana", "PagerDuty", "Go"],
    },
    {
      id: "infra",
      title: "Infrastructure Dev",
      available: true,
      techs: ["Terraform", "Ansible", "Pulumi", "Linux"],
    },
    {
      id: "kubernetes",
      title: "Kubernetes Engineer",
      available: true,
      techs: ["Kubernetes", "Helm", "Istio", "Docker"],
    },
    {
      id: "aws-dev",
      title: "AWS Specialist",
      available: true,
      techs: ["EC2", "Lambda", "S3", "CloudFormation"],
    },
    {
      id: "gcp-dev",
      title: "GCP Specialist",
      available: true,
      techs: ["GKE", "BigQuery", "Cloud Run", "Pub/Sub"],
    },
    {
      id: "azure-dev",
      title: "Azure Specialist",
      available: true,
      techs: ["Azure DevOps", "AKS", "Bicep", "Azure Functions"],
    },
    {
      id: "devsecops",
      title: "DevSecOps Engineer",
      available: true,
      techs: ["Snyk", "Vault", "SonarQube", "Trivy"],
    },
    {
      id: "platform-engineer",
      title: "Platform Engineer",
      available: false,
      techs: ["Backstage", "Kubernetes", "Terraform", "ArgoCD"],
    },
  ],
  datascience: [
    {
      id: "data-analyst",
      title: "Data Analyst",
      available: true,
      techs: ["Python", "Pandas", "Excel", "Tableau"],
    },
    {
      id: "ds-data-scientist",
      title: "Data Scientist",
      available: true,
      techs: ["Python", "Scikit-learn", "NumPy", "Jupyter"],
    },
    {
      id: "ds-data-engineer",
      title: "Data Engineer",
      available: true,
      techs: ["Spark", "Kafka", "Airflow", "dbt"],
    },
    {
      id: "bi-developer",
      title: "BI Developer",
      available: true,
      techs: ["Power BI", "Tableau", "SQL", "DAX"],
    },
    {
      id: "ml-analyst",
      title: "ML Analyst",
      available: true,
      techs: ["Python", "Scikit-learn", "Pandas", "Matplotlib"],
    },
    {
      id: "data-architect",
      title: "Data Architect",
      available: true,
      techs: ["Snowflake", "BigQuery", "dbt", "SQL"],
    },
    {
      id: "analytics-engineer",
      title: "Analytics Engineer",
      available: true,
      techs: ["dbt", "SQL", "Looker", "Airflow"],
    },
    {
      id: "statistician",
      title: "Statistician",
      available: false,
      techs: ["R", "Python", "SPSS", "SAS"],
    },
  ],
  gamedev: [
    {
      id: "unity",
      title: "Unity Dev",
      available: true,
      techs: ["C#", "Unity", "Shader Graph", "Physics"],
    },
    {
      id: "unreal",
      title: "Unreal Dev",
      available: true,
      techs: ["C++", "Unreal Engine", "Blueprints", "Nanite"],
    },
    {
      id: "web-game",
      title: "Web Game Dev",
      available: true,
      techs: ["Phaser.js", "Three.js", "WebGL", "JavaScript"],
    },
    {
      id: "game-designer",
      title: "Game Designer",
      available: true,
      techs: ["Unity", "Figma", "Twine", "GDD"],
    },
    {
      id: "godot",
      title: "Godot Developer",
      available: true,
      techs: ["GDScript", "Godot", "C#", "Shaders"],
    },
    {
      id: "game-ai",
      title: "Game AI Developer",
      available: true,
      techs: ["C++", "Behavior Trees", "NavMesh", "GOAP"],
    },
    {
      id: "shader-dev",
      title: "Shader / Graphics Dev",
      available: true,
      techs: ["HLSL", "GLSL", "Vulkan", "Unity URP"],
    },
    {
      id: "game-backend",
      title: "Game Backend Dev",
      available: true,
      techs: ["Node.js", "WebSockets", "Redis", "PlayFab"],
    },
    {
      id: "xr-dev",
      title: "XR / AR / VR Dev",
      available: true,
      techs: ["Unity XR", "ARKit", "OpenXR", "WebXR"],
    },
    {
      id: "gameplay-engineer",
      title: "Gameplay Engineer",
      available: true,
      techs: ["C++", "Unreal", "C#", "Unity"],
    },
    {
      id: "tools-dev",
      title: "Game Tools Developer",
      available: false,
      techs: ["C#", "Python", "Unity Editor", "Qt"],
    },
  ],
  qa: [
    {
      id: "automation",
      title: "Automation Engineer",
      available: true,
      techs: ["Selenium", "Cypress", "Jest", "Playwright"],
    },
    {
      id: "manual",
      title: "Manual Tester",
      available: true,
      techs: ["Jira", "TestRail", "Postman", "BrowserStack"],
    },
    {
      id: "performance",
      title: "Performance Tester",
      available: true,
      techs: ["JMeter", "k6", "Grafana", "Locust"],
    },
    {
      id: "security-qa",
      title: "Security Tester",
      available: true,
      techs: ["Burp Suite", "OWASP ZAP", "Metasploit", "Nmap"],
    },
    {
      id: "mobile-qa",
      title: "Mobile QA Engineer",
      available: true,
      techs: ["Appium", "XCTest", "Espresso", "BrowserStack"],
    },
    {
      id: "api-qa",
      title: "API Tester",
      available: true,
      techs: ["Postman", "REST Assured", "Newman", "Swagger"],
    },
    {
      id: "sdet",
      title: "SDET",
      available: true,
      techs: ["Java", "Selenium", "TestNG", "CI/CD"],
    },
    {
      id: "chaos-engineer",
      title: "Chaos Engineer",
      available: true,
      techs: ["Chaos Monkey", "Gremlin", "Kubernetes", "Prometheus"],
    },
    {
      id: "accessibility-qa",
      title: "Accessibility Tester",
      available: true,
      techs: ["axe", "WCAG", "NVDA", "Lighthouse"],
    },
    {
      id: "qa-lead",
      title: "QA Lead",
      available: false,
      techs: ["Jira", "TestRail", "Agile", "CI/CD"],
    },
  ],
  languages: [
    {
      id: "python",
      title: "Python",
      available: true,
      techs: ["Python", "pip", "venv", "pytest"],
    },
    {
      id: "javascript",
      title: "JavaScript",
      available: true,
      techs: ["JavaScript", "ES2022+", "DOM", "Node.js"],
    },
    {
      id: "typescript",
      title: "TypeScript",
      available: true,
      techs: ["TypeScript", "Types", "Generics", "tsconfig"],
    },
    {
      id: "go",
      title: "Go",
      available: true,
      techs: ["Go", "Goroutines", "Modules", "Std Library"],
    },
    {
      id: "rust",
      title: "Rust",
      available: true,
      techs: ["Rust", "Ownership", "Cargo", "Traits"],
    },
    {
      id: "java",
      title: "Java",
      available: true,
      techs: ["Java", "JVM", "OOP", "Streams"],
    },
    {
      id: "cpp",
      title: "C++",
      available: true,
      techs: ["C++", "STL", "RAII", "Templates"],
    },
    {
      id: "csharp",
      title: "C#",
      available: true,
      techs: ["C#", ".NET", "LINQ", "async/await"],
    },
    {
      id: "ruby",
      title: "Ruby",
      available: false,
      techs: ["Ruby", "Gems", "Blocks", "Metaprogramming"],
    },
    {
      id: "php",
      title: "PHP",
      available: false,
      techs: ["PHP", "Composer", "PSR", "OOP"],
    },
    {
      id: "c",
      title: "C",
      available: true,
      techs: ["C", "Pointers", "Make", "gdb"],
    },
    {
      id: "kotlin",
      title: "Kotlin",
      available: true,
      techs: ["Kotlin", "Null Safety", "Coroutines", "Extensions"],
    },
    {
      id: "swift",
      title: "Swift",
      available: true,
      techs: ["Swift", "Optionals", "Protocols", "Concurrency"],
    },
    {
      id: "dart",
      title: "Dart",
      available: true,
      techs: ["Dart", "Async", "Null Safety", "pub"],
    },
    {
      id: "elixir",
      title: "Elixir",
      available: true,
      techs: ["Elixir", "OTP", "Pattern Matching", "Mix"],
    },
    {
      id: "scala",
      title: "Scala",
      available: false,
      techs: ["Scala", "FP", "sbt", "Akka"],
    },
    {
      id: "haskell",
      title: "Haskell",
      available: false,
      techs: ["Haskell", "Monads", "Cabal", "Type Classes"],
    },
    {
      id: "lua",
      title: "Lua",
      available: false,
      techs: ["Lua", "Tables", "Coroutines", "LuaJIT"],
    },
  ],
  web3: [
    {
      id: "dapp-developer",
      title: "dApp Developer",
      available: true,
      techs: ["Solidity", "ethers.js", "React", "MetaMask"],
    },
    {
      id: "web3-frontend",
      title: "Web3 Frontend",
      available: true,
      techs: ["wagmi", "viem", "RainbowKit", "React"],
    },
    {
      id: "defi-developer",
      title: "DeFi Developer",
      available: true,
      techs: ["Solidity", "Foundry", "Uniswap", "Oracles"],
    },
    {
      id: "nft-developer",
      title: "NFT Developer",
      available: true,
      techs: ["ERC-721", "IPFS", "OpenZeppelin", "Solidity"],
    },
    {
      id: "web3-fullstack",
      title: "Web3 Full Stack",
      available: true,
      techs: ["Solidity", "Next.js", "Hardhat", "The Graph"],
    },
    {
      id: "wallet-developer",
      title: "Wallet Developer",
      available: false,
      techs: ["EIP-1193", "WalletConnect", "Keys", "Security"],
    },
    {
      id: "gamefi-developer",
      title: "GameFi Developer",
      available: true,
      techs: ["Solidity", "Unity", "NFTs", "web3.js"],
    },
    {
      id: "dao-developer",
      title: "DAO Developer",
      available: true,
      techs: ["Solidity", "Governance", "Snapshot", "Aragon"],
    },
    {
      id: "zk-developer",
      title: "ZK Developer",
      available: true,
      techs: ["Circom", "ZK-SNARKs", "Noir", "Solidity"],
    },
    {
      id: "web3-indexer",
      title: "Web3 Data / Indexer",
      available: false,
      techs: ["The Graph", "GraphQL", "Subgraphs", "Ponder"],
    },
  ],
  blockchain: [
    {
      id: "smart-contract",
      title: "Smart Contract Dev",
      available: true,
      techs: ["Solidity", "Foundry", "Hardhat", "OpenZeppelin"],
    },
    {
      id: "ethereum-dev",
      title: "Ethereum Developer",
      available: true,
      techs: ["Solidity", "EVM", "Geth", "ethers.js"],
    },
    {
      id: "solana-dev",
      title: "Solana Developer",
      available: true,
      techs: ["Rust", "Anchor", "Solana", "SPL"],
    },
    {
      id: "blockchain-core",
      title: "Blockchain Core Dev",
      available: true,
      techs: ["Rust", "Go", "Consensus", "P2P"],
    },
    {
      id: "blockchain-security",
      title: "Blockchain Security",
      available: true,
      techs: ["Solidity", "Auditing", "Slither", "Echidna"],
    },
    {
      id: "chain-architect",
      title: "Chain Architect",
      available: false,
      techs: ["Cosmos SDK", "Substrate", "Tendermint", "Consensus"],
    },
    {
      id: "bitcoin-dev",
      title: "Bitcoin Developer",
      available: true,
      techs: ["Bitcoin", "Script", "Lightning", "C++"],
    },
    {
      id: "cosmos-dev",
      title: "Cosmos Developer",
      available: true,
      techs: ["Cosmos SDK", "Go", "Tendermint", "IBC"],
    },
    {
      id: "move-developer",
      title: "Move Developer",
      available: true,
      techs: ["Move", "Aptos", "Sui", "Rust"],
    },
    {
      id: "layer2-dev",
      title: "Layer 2 Developer",
      available: false,
      techs: ["Optimism", "zkSync", "Rollups", "Solidity"],
    },
  ],
  cybersecurity: [
    {
      id: "pentester",
      title: "Penetration Tester",
      available: true,
      techs: ["Kali", "Burp Suite", "Metasploit", "Nmap"],
    },
    {
      id: "soc-analyst",
      title: "SOC Analyst",
      available: true,
      techs: ["SIEM", "Splunk", "IDS/IPS", "Threat Intel"],
    },
    {
      id: "appsec-engineer",
      title: "AppSec Engineer",
      available: true,
      techs: ["OWASP", "SAST", "DAST", "Threat Modeling"],
    },
    {
      id: "red-team",
      title: "Red Team Operator",
      available: true,
      techs: ["C2", "OPSEC", "Evasion", "Active Directory"],
    },
    {
      id: "blue-team",
      title: "Blue Team Defender",
      available: true,
      techs: ["EDR", "SIEM", "Forensics", "Hardening"],
    },
    {
      id: "cloud-security",
      title: "Cloud Security Engineer",
      available: true,
      techs: ["AWS", "IAM", "CSPM", "Zero Trust"],
    },
    {
      id: "malware-analyst",
      title: "Malware Analyst",
      available: false,
      techs: ["Reverse Engineering", "Ghidra", "Assembly", "Sandboxing"],
    },
    {
      id: "grc-analyst",
      title: "GRC Analyst",
      available: false,
      techs: ["ISO 27001", "SOC 2", "NIST", "Risk"],
    },
    {
      id: "security-architect",
      title: "Security Architect",
      available: true,
      techs: ["Zero Trust", "Threat Modeling", "IAM", "Architecture"],
    },
    {
      id: "threat-hunter",
      title: "Threat Hunter",
      available: true,
      techs: ["SIEM", "MITRE ATT&CK", "EDR", "Threat Intel"],
    },
    {
      id: "forensics-analyst",
      title: "Digital Forensics Analyst",
      available: true,
      techs: ["Forensics", "Autopsy", "Volatility", "Disk Imaging"],
    },
    {
      id: "bug-bounty-hunter",
      title: "Bug Bounty Hunter",
      available: false,
      techs: ["Burp Suite", "Recon", "OWASP", "Fuzzing"],
    },
  ],
  cloud: [
    {
      id: "aws-architect",
      title: "AWS Solutions Architect",
      available: true,
      techs: ["AWS", "EC2", "VPC", "CloudFormation"],
    },
    {
      id: "azure-architect",
      title: "Azure Architect",
      available: true,
      techs: ["Azure", "AKS", "Bicep", "Entra ID"],
    },
    {
      id: "gcp-architect",
      title: "GCP Architect",
      available: true,
      techs: ["GCP", "GKE", "BigQuery", "Terraform"],
    },
    {
      id: "serverless-dev",
      title: "Serverless Developer",
      available: true,
      techs: ["Lambda", "API Gateway", "DynamoDB", "SAM"],
    },
    {
      id: "cloud-native",
      title: "Cloud Native Engineer",
      available: true,
      techs: ["Kubernetes", "Docker", "Helm", "Istio"],
    },
    {
      id: "finops-engineer",
      title: "FinOps Engineer",
      available: false,
      techs: ["Cost Management", "Tagging", "Budgets", "Optimization"],
    },
    {
      id: "multi-cloud-architect",
      title: "Multi-Cloud Architect",
      available: true,
      techs: ["AWS", "Azure", "GCP", "Terraform"],
    },
    {
      id: "cloud-migration",
      title: "Cloud Migration Specialist",
      available: true,
      techs: ["Migration", "Assessment", "Lift & Shift", "Refactoring"],
    },
    {
      id: "edge-engineer",
      title: "Edge Computing Engineer",
      available: true,
      techs: ["Cloudflare", "CDN", "Edge Functions", "WASM"],
    },
    {
      id: "observability-engineer",
      title: "Observability Engineer",
      available: false,
      techs: ["Prometheus", "Grafana", "OpenTelemetry", "Datadog"],
    },
  ],
  database: [
    {
      id: "postgres-dba",
      title: "PostgreSQL DBA",
      available: true,
      techs: ["PostgreSQL", "psql", "Replication", "Tuning"],
    },
    {
      id: "mysql-dba",
      title: "MySQL DBA",
      available: true,
      techs: ["MySQL", "InnoDB", "Replication", "Backup"],
    },
    {
      id: "mongodb-admin",
      title: "MongoDB Admin",
      available: true,
      techs: ["MongoDB", "Atlas", "Sharding", "Aggregation"],
    },
    {
      id: "data-modeler",
      title: "Data Modeler",
      available: true,
      techs: ["ER Modeling", "Normalization", "SQL", "Schemas"],
    },
    {
      id: "nosql-engineer",
      title: "NoSQL Engineer",
      available: true,
      techs: ["MongoDB", "Cassandra", "Redis", "DynamoDB"],
    },
    {
      id: "db-reliability",
      title: "Database Reliability Eng",
      available: false,
      techs: ["HA", "Replication", "Monitoring", "Backup"],
    },
    {
      id: "redis-engineer",
      title: "Redis Engineer",
      available: true,
      techs: ["Redis", "Caching", "Pub/Sub", "Cluster"],
    },
    {
      id: "cassandra-engineer",
      title: "Cassandra Engineer",
      available: true,
      techs: ["Cassandra", "CQL", "Distributed", "Replication"],
    },
    {
      id: "vector-db-engineer",
      title: "Vector DB Engineer",
      available: true,
      techs: ["pgvector", "Pinecone", "Embeddings", "ANN"],
    },
    {
      id: "graph-db-engineer",
      title: "Graph DB Engineer",
      available: false,
      techs: ["Neo4j", "Cypher", "Graph Models", "GQL"],
    },
  ],
  quantum: [
    {
      id: "quantum-developer",
      title: "Quantum Developer",
      available: true,
      techs: ["Qiskit", "Python", "Quantum Gates", "IBM Q"],
    },
    {
      id: "quantum-algorithms",
      title: "Quantum Algorithms",
      available: true,
      techs: ["Shor", "Grover", "Linear Algebra", "Complexity"],
    },
    {
      id: "quantum-ml",
      title: "Quantum ML",
      available: true,
      techs: ["PennyLane", "Qiskit ML", "VQC", "PyTorch"],
    },
    {
      id: "quantum-crypto",
      title: "Quantum Cryptography",
      available: false,
      techs: ["QKD", "Post-Quantum", "BB84", "Lattices"],
    },
    {
      id: "quantum-researcher",
      title: "Quantum Researcher",
      available: false,
      techs: ["Q#", "Cirq", "Hamiltonians", "Error Correction"],
    },
    {
      id: "quantum-hardware",
      title: "Quantum Hardware Engineer",
      available: true,
      techs: ["Superconducting", "Ion Traps", "Pulse", "Calibration"],
    },
    {
      id: "quantum-optimization",
      title: "Quantum Optimization",
      available: true,
      techs: ["QAOA", "Annealing", "D-Wave", "Ising"],
    },
    {
      id: "quantum-simulation",
      title: "Quantum Simulation",
      available: false,
      techs: ["VQE", "Chemistry", "Hamiltonians", "Qiskit"],
    },
  ],
};

// ─── Layer Schema ────────────────────────────────────────────────────────────
// {
//   id: string
//   title: string
//   order: number
//   techs: string[]
//   description: string
//   topics: string[]
//   resources: { label: string, platform: string, type: "docs"|"course"|"video"|"book" }[]
//   challenge: string        — hands-on mini project for this layer
//   estimatedTime: string
// }
// ─────────────────────────────────────────────────────────────────────────────
