/**
 * Every capstone brief, checked for the mistakes that would only show up when
 * a learner hits them: a rubric that does not sum to 100, duplicate ids, a
 * layer from another track, or a file check that a correct project can never
 * pass.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { briefs } from "../../seeders/capstones/index.js";
import { evaluateSubmission } from "../../modules/capstone/lib/autoChecks.js";

const roadmap = (file) =>
  JSON.parse(
    readFileSync(
      new URL(`../../../src/data/roadmaps/${file}.json`, import.meta.url),
      "utf8",
    ),
  );

// A realistic, correct project layout per track: every automated check must pass on it.
const LAYOUTS = {
  "web3-indexer": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "ponder.config.ts",
    "tests/handler.test.ts",
  ],
  "zk-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "circuits/proof.circom",
    "test/proof.test.js",
  ],
  "dao-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "test/Governor.test.js",
  ],
  "gamefi-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "test/Game.test.js",
  ],
  "wallet-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    "manifest.json",
    "app.test.js",
  ],
  "web3-fullstack": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "subgraph/subgraph.yaml",
    "app/page.tsx",
    "test/Contract.test.js",
  ],
  "nft-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    "test/Nft.test.js",
  ],
  "defi-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    "foundry.toml",
    "test/Pool.t.sol",
  ],
  "web3-frontend": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "app.test.js",
  ],
  "dapp-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    "scripts/deploy.js",
    "test/Dapp.t.js",
  ],
  c: ["README.md", ".github/workflows/ci.yml", "Makefile", "src/main.c"],
  cpp: [
    "README.md",
    ".github/workflows/ci.yml",
    "CMakeLists.txt",
    "src/main.cpp",
  ],
  csharp: [
    "README.md",
    ".github/workflows/ci.yml",
    "App.csproj",
    "App.Tests/AppTests.cs",
  ],
  dart: [
    "README.md",
    ".github/workflows/ci.yml",
    "pubspec.yaml",
    "test/app_test.dart",
  ],
  go: ["README.md", ".github/workflows/ci.yml", "go.mod", "app_test.go"],
  java: [
    "README.md",
    ".github/workflows/ci.yml",
    "pom.xml",
    "src/test/java/AppTest.java",
  ],
  javascript: [
    "README.md",
    ".github/workflows/ci.yml",
    "package.json",
    "app.test.js",
  ],
  kotlin: [
    "README.md",
    ".github/workflows/ci.yml",
    "build.gradle.kts",
    "src/test/kotlin/AppTest.kt",
  ],
  php: [
    "README.md",
    ".github/workflows/ci.yml",
    "composer.json",
    "docker-compose.yml",
    "tests/AppTest.php",
  ],
  python: [
    "README.md",
    ".github/workflows/ci.yml",
    "pyproject.toml",
    "tests/test_app.py",
  ],
  ruby: [
    "README.md",
    ".github/workflows/ci.yml",
    "app.gemspec",
    "spec/app_spec.rb",
  ],
  rust: ["README.md", ".github/workflows/ci.yml", "Cargo.toml", "tests/app.rs"],
  swift: [
    "README.md",
    ".github/workflows/ci.yml",
    "Package.swift",
    "Tests/AppTests/AppTests.swift",
  ],
  typescript: [
    "README.md",
    ".github/workflows/ci.yml",
    "tsconfig.json",
    "app.test.ts",
  ],
  "quantum-algorithms": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "quantum-crypto": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
    ".env.example",
  ],
  "quantum-developer": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
    ".env.example",
  ],
  "quantum-hardware": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "quantum-ml": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "quantum-optimization": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "quantum-researcher": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "quantum-simulation": [
    "README.md",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "qa-lead": [
    "README.md",
    ".github/workflows/ci.yml",
    "docs/test-strategy.md",
    "docs/risk-matrix.md",
    "docs/onboarding-mentorship.md",
    "docs/quality-metrics.md",
    "docs/three-amigos-charter.md",
    "docs/automation-standards.md",
    "docs/postmortem.md",
    "docs/annual-roadmap.md",
  ],
  "accessibility-qa": [
    "README.md",
    ".github/workflows/ci.yml",
    "package.json",
    "tests/aria.test.js",
    "tests/keyboard.test.js",
    "docs/screen-reader-audit.md",
    "docs/contrast-report.md",
    ".lighthouserc.json",
    "docs/vpat.md",
  ],
  "chaos-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "docs/experiments/latency.md",
    "chaos/network.yml",
    "network/partition.py",
    "experiments/db_chaos_kill.py",
    "monitoring/prometheus.yml",
    "dashboards/chaos.json",
    "docs/gameday-report.md",
  ],
  sdet: [
    "README.md",
    ".github/workflows/ci.yml",
    "pom.xml",
    ".env.example",
    "src/main/java/App.java",
    "src/test/resources/login.feature",
    "src/test/java/StepDefs.java",
    "src/test/java/ApiTest.java",
    "src/test/java/TestPostgresContainer.java",
    "src/test/java/MockServer.java",
  ],
  "api-qa": [
    "README.md",
    ".github/workflows/ci.yml",
    "pom.xml",
    "src/test/java/ApiTest.java",
    "src/test/resources/schemas/user.json",
    "pacts/consumer-provider.json",
    "src/test/java/WireMockTest.java",
    "collection.postman_collection.json",
    ".env.example",
  ],
  "mobile-qa": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "screens/login.py",
    "tests/test_flows_login.py",
    "tests/test_gestures_swipe.py",
    "tests/test_performance_startup.py",
    "conftest.py",
    "Fastfile",
  ],
  "security-qa": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "docker-compose.yml",
    "zap/scan.py",
    "tests/test_injection_sql.py",
    "tests/test_authorization_bola.py",
    "docs/threat-model.md",
    "reports/findings.json",
  ],
  performance: [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "scripts/login.js",
    "scenarios/ramp_up.js",
    "data/users.csv",
    "dashboards/perf.json",
    "docs/analysis-report.md",
  ],
  manual: [
    "README.md",
    ".github/workflows/ci.yml",
    "docs/test-plan.md",
    "test-cases/login.md",
    "bug-reports/BUG-1.md",
    "collection.postman_collection.json",
    "sql/seed.sql",
    "docs/exploratory-session.md",
    "docs/accessibility-audit.md",
    "docs/rtm.md",
  ],
  automation: [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "Dockerfile",
    "conftest.py",
    "pages/login_page.py",
    "tests/test_ui_login.py",
    "tests/test_api_users.py",
    "data/users.json",
  ],
  "tools-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "src/tool.py",
    "src/qt_app.py",
    "tests/test_tool.py",
  ],
  "gameplay-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "Source/Game/Character.cpp",
    "Source/Tests/Character.test.cpp",
  ],
  "xr-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "Assets/Scripts/Interaction.cs",
    "Assets/Scripts.meta",
    "Assets/Tests/InteractionTests.cs",
  ],
  "game-backend": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    ".env.example",
    "tests/server.test.js",
  ],
  "shader-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "Assets/Editor/ShaderInspector.cs",
    "Assets/Shaders/toon.shader",
  ],
  "game-ai": [
    "README.md",
    ".github/workflows/ci.yml",
    "Source/AI/BehaviorTree.cpp",
    "Source/Tests/BehaviorTree.test.cpp",
  ],
  godot: [
    "README.md",
    ".github/workflows/ci.yml",
    "project.godot",
    "test/test_movement.gd",
  ],
  "game-designer": [
    "README.md",
    ".github/workflows/ci.yml",
    "docs/GDD.md",
    "docs/economy.csv",
    "Assets/scenes/level1.tscn",
    "docs/dialogue.tw",
    "docs/playtest-notes.md",
    "tests/test_balance.gd",
  ],
  "web-game": [
    "README.md",
    ".github/workflows/ci.yml",
    "package.json",
    "src/game.test.js",
  ],
  unreal: [
    "README.md",
    ".github/workflows/ci.yml",
    "Source/Game/Player.cpp",
    "Source/Tests/Player.test.cpp",
    "game.uproject",
  ],
  unity: [
    "README.md",
    ".github/workflows/ci.yml",
    "Assets/Scripts/Editor/Tests/PlayerTests.cs",
    "Assets/Scripts.meta",
  ],
  "platform-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "catalog-info.yaml",
    "templates/service/template.yaml",
    "crossplane/claim.yaml",
    "gitops/app-of-apps.yaml",
    "charts/service/Chart.yaml",
    "policies/policy.rego",
    "dashboards/service.json",
    "docker-compose.yml",
  ],
  devsecops: [
    "README.md",
    ".github/workflows/ci.yml",
    "config/scan.json",
    "policies/deny.rego",
    "Dockerfile",
    "docker-compose.yml",
  ],
  "azure-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "infra/main.bicep",
    "src/index.js",
    "azure-pipelines.yml",
    "docker-compose.yml",
  ],
  "gcp-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "main.tf",
    "Dockerfile",
    "src/index.js",
    "docker-compose.yml",
    "tests/app.test.js",
  ],
  "aws-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "template.yaml",
    "src/index.js",
    "docker-compose.yml",
    "tests/app.test.js",
  ],
  kubernetes: [
    "README.md",
    ".github/workflows/ci.yml",
    "Dockerfile",
    "k8s/deployment.yaml",
    "charts/app/Chart.yaml",
    "k8s/ingress.yaml",
    "istio/virtualservice.yaml",
    "k8s/rbac.yaml",
    "k8s/hpa.yaml",
    "gitops/app.yaml",
  ],
  infra: [
    "README.md",
    ".github/workflows/ci.yml",
    "terraform/main.tf",
    "ansible/playbook.yml",
    "terraform/environments/prod/main.tf",
    "pulumi/index.ts",
    "docker-compose.yml",
    ".env.example",
  ],
  sre: [
    "README.md",
    ".github/workflows/ci.yml",
    "go.mod",
    "service_test.go",
    "prometheus/alerts.yml",
    "grafana/dashboard.json",
    "docker-compose.yml",
    "docs/runbook.md",
  ],
  cicd: [
    "README.md",
    ".github/workflows/ci.yml",
    "Jenkinsfile",
    "charts/app/Chart.yaml",
    "gitops/app.yaml",
    "docker-compose.yml",
    "Dockerfile",
    ".env.example",
  ],
  cloud: [
    "README.md",
    ".github/workflows/ci.yml",
    "main.tf",
    "Dockerfile",
    "docker-compose.yml",
    "k8s/deployment.yaml",
    "monitoring/alerts.yaml",
    ".env.example",
  ],
  "analytics-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "dbt/models/staging/stg_orders.sql",
    "dbt/models/marts/fct_orders.sql",
    "dbt/models/staging/stg_orders.yml",
    "dbt/tests/assert_positive.sql",
    "looker/orders.lkml",
    "dags/orders_dag.py",
    "tests/test_models.py",
  ],
  "bi-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    "sql/views/sales.sql",
    "dax/measures.dax",
    "dashboards/sales.pbix",
    "security/rls.sql",
    "docs/performance.md",
    "docs/style_guide.md",
    "scripts/gen_data.py",
    "tests/test_queries.py",
  ],
  "data-analyst": [
    "README.md",
    ".github/workflows/ci.yml",
    "src/clean.py",
    "models/staging.sql",
    "sql/report.sql",
    "dashboards/dashboard.html",
    "reports/executive_summary.md",
    "tests/schema.sql",
    "tests/test_analysis.py",
  ],
  "data-architect": [
    "README.md",
    ".github/workflows/ci.yml",
    "docs/architecture/diagram.png",
    "docs/adr/0001-record.md",
    "ddl/3nf/schema.sql",
    "ddl/dimensional/star.sql",
    "security/rbac.sql",
    "dbt/models/core/dim_customer.sql",
    "governance/catalog.yml",
    "tests/test_arch.py",
  ],
  "ds-data-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "src/ingest/extract.py",
    "dbt/models/staging/stg_events.sql",
    "dbt/models/marts/fct_events.sql",
    "dbt/tests/assert_unique.sql",
    "dags/pipeline_dag.py",
    "docker-compose.yml",
    ".env.example",
    "tests/test_pipeline.py",
  ],
  "ds-data-scientist": [
    "README.md",
    ".github/workflows/ci.yml",
    "notebooks/eda.ipynb",
    "src/features/build_features.py",
    "src/models/clustering.py",
    "src/models/forecasting.py",
    "src/models/evaluate.py",
    "templates/report.html",
    "main.py",
    "tests/test_models.py",
  ],
  "ml-analyst": [
    "README.md",
    ".github/workflows/ci.yml",
    "notebooks/eda.ipynb",
    "src/pipelines/preprocessing.py",
    "src/models/train.py",
    "src/models/tune.py",
    "src/explainability/shap_report.py",
    "src/models/clustering.py",
    "reports/model_card.md",
    "tests/test_models.py",
  ],
  statistician: [
    "README.md",
    ".github/workflows/ci.yml",
    "R/load_data.R",
    "R/regression.R",
    "R/survival.R",
    "R/bayesian.R",
    "R/multivariate.R",
    "reports/consulting_report.pdf",
    "tests/testthat/test-regression.R",
  ],
  "cassandra-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "schema.cql",
    "cassandra_client.py",
    "security.cql",
    "scripts/nodetool_ops.sh",
    "jmx_exporter.yml",
    "scripts/stress_test.sh",
    "docker-compose.yml",
  ],
  "data-modeler": [
    "README.md",
    ".github/workflows/ci.yml",
    "migrations/V1__oltp_schema.sql",
    "migrations/V2__olap_star_schema.sql",
    "migrations/V3__temporal_tables.sql",
    "dynamodb_single_table_schema.json",
    "triggers.sql",
    "docs/data_catalog.md",
    "er_diagram.png",
  ],
  "db-reliability": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "alerts.yml",
    "scripts/validate_backup.sh",
    "scripts/online_migration.sh",
    "docs/runbooks/incident.md",
    "scripts/chaos_test.sh",
    "vault_secrets.sh",
    "capacity_model.py",
  ],
  "graph-db-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "schema.cypher",
    "queries.cypher",
    "indexes.cypher",
    "gds_analytics.py",
    "app.py",
    "security.cypher",
    "scripts/backup.sh",
    "test_graph.py",
  ],
  "mongodb-admin": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "init_sharding.js",
    "indexes.js",
    "aggregation.js",
    "security_rbac.js",
    "scripts/backup_restore.sh",
    "transaction_demo.js",
    "scripts/profiling.js",
  ],
  "mysql-dba": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "proxysql.cnf",
    "my.cnf",
    "init_users.sql",
    "scripts/backup.sh",
    "schema.sql",
    "scripts/diagnostics.sql",
    "scripts/test_failover.sh",
  ],
  "nosql-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    ".env.example",
    "docker-compose.yml",
    "app.js",
    "redis_service.js",
    "schema.cql",
    "sync_service.js",
    "app.test.js",
    "prometheus.yml",
  ],
  "postgres-dba": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "pgbouncer.ini",
    "patroni.yml",
    "scripts/restore_pitr.sh",
    "schema.sql",
    "postgresql.conf",
    "partitioning.sql",
    "scripts/backup.sh",
    "scripts/test_failover.sh",
  ],
  "redis-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "cache_service.js",
    "stream_consumer.js",
    "search_indexer.js",
    "scripts/eviction.lua",
    "redis.conf",
    "users.acl",
    "tests/cache.test.js",
  ],
  "vector-db-engineer": [
    "README.md",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "schema.sql",
    "indexes.sql",
    "ingest.py",
    "rag_pipeline.py",
    "hybrid_search.py",
    "evaluate_recall.py",
    "test_recall.py",
  ],
  "malware-analyst": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "analyzer/scan.py",
    "rules/sample.yar",
    "tests/test_scan.py",
  ],
  "grc-analyst": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "tests/controls.test.js",
  ],
  "security-architect": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "main.tf",
    "tests/test_model.py",

    "docs/architecture.md",
  ],
  "threat-hunter": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "hunts/hunt.yml",
    "tests/test_hunts.py",

    "playbooks/hunt-1.md",
  ],
  "forensics-analyst": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "tests/test_parse.py",

    "docs/forensic-report.md",
  ],
  "bug-bounty-hunter": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "Dockerfile",
    "templates/check.yaml",
    "tests/test_scan.py",

    "reports/example.md",
  ],
  pentester: [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "tools/scan.py",
    "tests/test_scan.py",

    "docs/pentest-report.md",
  ],
  "soc-analyst": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "rules/local.rules",
    "tests/test_rules.py",

    "queries/example.spl",

    "playbooks/ir-1.md",
  ],
  "appsec-engineer": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "rules/semgrep.yml",
    "tests/app.test.js",

    "docs/threat-model.md",
  ],
  "red-team": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "src/main.go",
    "tests/test_c2.py",

    "emulation/plan.yml",
  ],
  "blue-team": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "sigma/rule.yml",
    "config/sysmon.xml",
    "rules/local.rules",
    "tests/test_detect.py",
    "playbooks/ir-1.md",
  ],
  "cloud-security": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "main.tf",
    "policy/deny.rego",
    "tests/test_policy.py",
    "playbooks/ir-1.md",
  ],
  "aws-architect": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "template.yaml",
    "tests/infra.test.ts",
  ],
  "azure-architect": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "infra/main.bicep",
    "tests/infra.test.ts",
  ],
  "gcp-architect": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "main.tf",
    "tests/infra.test.ts",
  ],
  "serverless-dev": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "template.yaml",
    "src/handler.js",
    "tests/handler.test.js",
  ],
  "cloud-native": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "Dockerfile",
    "charts/app/Chart.yaml",
    "argocd/Application.yaml",
    "tests/app.test.js",
  ],
  "finops-engineer": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "Dockerfile",
    "tests/test_cost.py",
  ],
  "multi-cloud-architect": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "main.tf",
    "argocd/ApplicationSet.yaml",
    "tests/plan.test.ts",
  ],
  "cloud-migration": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "tests/test_plan.py",
  ],
  "edge-engineer": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "wrangler.toml",
    "src/worker.ts",
    "tests/worker.test.ts",
  ],
  "observability-engineer": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "docker-compose.yml",
    "tests/alerts.test.ts",
  ],
  "ml-engineer": [
    "README.md",
    ".env.example",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "data-scientist": [
    "README.md",
    ".env.example",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "ai-developer": [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "nlp-engineer": [
    "README.md",
    ".env.example",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "cv-engineer": [
    "README.md",
    ".env.example",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "llm-engineer": [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  mlops: [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "data-engineer": [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "rl-engineer": [
    "README.md",
    ".env.example",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "prompt-engineer": [
    "README.md",
    ".env.example",
    "Dockerfile",
    ".github/workflows/ci.yml",
    "tests/test_main.py",
  ],
  "api-dev": [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "src/app.js",
    "tests/notes.test.js",
  ],
  "node-dev": [
    "README.md",
    ".env.example",
    "compose.yaml",
    ".github/workflows/ci.yml",
    "prisma/schema.prisma",
    "src/server.ts",
    "test/links.test.ts",
  ],
  "python-backend": [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/test.yml",
    "pyproject.toml",
    "app/main.py",
    "tests/test_booking.py",
  ],
  "db-engineer": [
    "README.md",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "db/migrations/001_init.sql",
    "queries/revenue.sql",
    "tests/constraints.sql",
  ],
  "go-dev": [
    "README.md",
    "go.mod",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "cmd/api/main.go",
    "internal/stock/reserve_test.go",
  ],
  "rust-dev": [
    "README.md",
    "Cargo.toml",
    "compose.yaml",
    ".github/workflows/ci.yml",
    "src/main.rs",
    "tests/api.rs",
  ],
  "java-spring": [
    "README.md",
    "pom.xml",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "src/main/java/app/LoanService.java",
    "src/test/java/app/LoanServiceTest.java",
  ],
  "graphql-dev": [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "src/schema.graphql",
    "src/resolvers.ts",
    "test/recipes.test.ts",
  ],
  "grpc-dev": [
    "README.md",
    "buf.yaml",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "proto/ride/v1/ride.proto",
    "server/main.go",
  ],
  microservices: [
    "README.md",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "orders/Dockerfile",
    "payments/Dockerfile",
    "orders/src/app.js",
  ],
  "security-dev": [
    "README.md",
    "THREAT_MODEL.md",
    ".env.example",
    "docker-compose.yml",
    ".github/workflows/security.yml",
    "src/app.py",
    "tests/test_idor.py",
  ],
  "systems-dev": [
    "README.md",
    "CMakeLists.txt",
    ".github/workflows/ci.yml",
    "src/server.c",
    "tests/test_protocol.c",
  ],
  pern: [
    "README.md",
    ".github/workflows/ci.yml",
    "client/src/App.jsx",
    "server/src/app.js",
    "server/tests/expenses.test.js",
    "prisma/schema.prisma",
  ],
  t3: [
    "README.md",
    ".github/workflows/ci.yml",
    "src/pages/index.tsx",
    "src/server/api/routers/book.ts",
    "src/server/api/book.test.ts",
    "prisma/schema.prisma",
  ],
  "fullstack-engineer": [
    "README.md",
    "docker-compose.yml",
    ".github/workflows/ci.yml",
    "web/src/App.jsx",
    "api/src/app.js",
    "api/tests/tickets.test.js",
    "e2e/ticket.spec.ts",
  ],
  mean: [
    "README.md",
    ".github/workflows/ci.yml",
    "client/src/app/app.component.ts",
    "client/src/app/events/events.service.spec.ts",
    "server/src/app.js",
  ],
  jamstack: [
    "README.md",
    ".github/workflows/ci.yml",
    "src/pages/index.jsx",
    "src/templates/session.jsx",
    "netlify/functions/attendee.js",
    "src/__tests__/session.test.jsx",
  ],
  "django-react": [
    "README.md",
    ".github/workflows/ci.yml",
    "backend/manage.py",
    "backend/recipes/tests.py",
    "frontend/src/App.jsx",
    "frontend/src/App.test.jsx",
  ],
  "rails-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "Gemfile",
    "app/models/opportunity.rb",
    "spec/models/opportunity_spec.rb",
    "spec/requests/applications_spec.rb",
  ],
  "next-fullstack": [
    "README.md",
    ".github/workflows/ci.yml",
    "app/page.tsx",
    "app/invoices/actions.ts",
    "tests/invoice-total.test.ts",
    "e2e/invoice.spec.ts",
  ],
  "sveltekit-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "src/routes/+page.svelte",
    "src/routes/habits/+page.server.ts",
    "src/lib/validation.test.ts",
    "tests/habit.spec.ts",
  ],
  "nuxt-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "app.vue",
    "pages/trips/[id].vue",
    "server/api/trips/index.get.ts",
    "tests/trips.test.ts",
  ],
  "astro-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "src/pages/docs/[...slug].astro",
    "src/content/config.ts",
    "src/lib/toc.test.ts",
    "tests/navigation.spec.ts",
  ],
  "laravel-vue": [
    "README.md",
    ".github/workflows/ci.yml",
    "app/Models/MaintenanceRequest.php",
    "tests/Feature/RequestWorkflowTest.php",
    "resources/js/App.vue",
  ],
  "remix-dev": [
    "README.md",
    ".github/workflows/ci.yml",
    "app/routes/workshops.$id.tsx",
    "app/models/booking.server.ts",
    "app/models/booking.test.ts",
    "e2e/booking.spec.ts",
  ],
  "smart-contract": [
    "README.md",
    "foundry.toml",
    ".github/workflows/ci.yml",
    "src/Escrow.sol",
    "test/Escrow.t.sol",
  ],
  "ethereum-dev": [
    "README.md",
    "hardhat.config.ts",
    ".github/workflows/ci.yml",
    "contracts/Emitter.sol",
    "src/indexer.ts",
    "test/indexer.test.ts",
  ],
  "solana-dev": [
    "README.md",
    "Anchor.toml",
    ".github/workflows/ci.yml",
    "programs/treasury/src/lib.rs",
    "tests/treasury.ts",
  ],
  "blockchain-core": [
    "README.md",
    "Cargo.toml",
    ".github/workflows/ci.yml",
    "src/main.rs",
    "tests/chain.rs",
  ],
  "blockchain-security": [
    "README.md",
    "foundry.toml",
    ".github/workflows/ci.yml",
    "AUDIT.md",
    "src/Vault.sol",
    "test/Vault.t.sol",
  ],
  "chain-architect": [
    "README.md",
    "go.mod",
    ".github/workflows/ci.yml",
    "proto/app/v1/state.proto",
    "x/app/module.go",
    "x/app/keeper/keeper_test.go",
  ],
  "bitcoin-dev": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "src/vault.js",
    "test/vault.test.js",
  ],
  "cosmos-dev": [
    "README.md",
    "go.mod",
    ".github/workflows/ci.yml",
    "proto/grants/v1/query.proto",
    "x/grants/module.go",
    "x/grants/keeper/keeper_test.go",
  ],
  "move-developer": [
    "README.md",
    ".github/workflows/ci.yml",
    "Move.toml",
    "sources/membership.move",
    "tests/membership_tests.move",
  ],
  "layer2-dev": [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "script/Deploy.s.sol",
    "test/Escrow.t.sol",
    "app/page.tsx",
  ],
  mern: [
    "README.md",
    ".env.example",
    ".github/workflows/ci.yml",
    "client/src/App.jsx",
    "server/src/app.js",
    "server/tests/boards.test.js",
  ],
  "react-native": [
    "README.md",
    "app.json",
    ".github/workflows/ci.yml",
    "App.tsx",
    "src/screens/Home.tsx",
    "__tests__/App.test.tsx",
  ],
  flutter: [
    "README.md",
    "pubspec.yaml",
    ".github/workflows/ci.yml",
    "lib/main.dart",
    "lib/screens/home.dart",
    "test/home_test.dart",
  ],
  ios: [
    "README.md",
    "Package.swift",
    ".github/workflows/ci.yml",
    "Sources/App/App.swift",
    "Sources/App/RecipeStore.swift",
    "Tests/AppTests/RecipeTests.swift",
  ],
  android: [
    "README.md",
    "app/src/main/AndroidManifest.xml",
    ".github/workflows/ci.yml",
    "app/src/main/java/app/MainActivity.kt",
    "app/src/test/java/app/PantryTest.kt",
  ],
  "kotlin-dev": [
    "README.md",
    "build.gradle.kts",
    ".github/workflows/ci.yml",
    "src/main/kotlin/App.kt",
    "src/test/kotlin/AppTest.kt",
  ],
  "swift-dev": [
    "README.md",
    "Package.swift",
    ".github/workflows/ci.yml",
    "Sources/App/App.swift",
    "Tests/AppTests/HabitTests.swift",
  ],
  maui: [
    "README.md",
    "App.csproj",
    ".github/workflows/ci.yml",
    "Views/MainPage.xaml",
    "ViewModels/JobViewModel.cs",
    "Tests/JobViewModelTests.cs",
  ],
  "pwa-dev": [
    "README.md",
    "manifest.json",
    "service-worker.js",
    ".github/workflows/ci.yml",
    "src/app.js",
    "test/app.test.js",
  ],
  ionic: [
    "README.md",
    ".github/workflows/ci.yml",
    "src/app/home/home.page.ts",
    "src/app/home/home.page.spec.ts",
  ],
};

describe.each(briefs.map((b) => [b.trackId, b]))(
  "capstone brief %s",
  (trackId, brief) => {
    const categoryLayers = roadmap(brief.categoryId)[trackId];

    it("belongs to a real track in its category", () => {
      expect(categoryLayers?.length).toBeGreaterThan(0);
    });

    it("has a rubric that sums to 100, with unique ids, each mapped to a layer of this track", () => {
      const layerIds = new Set(categoryLayers.map((l) => l.id));
      expect(brief.rubric.reduce((s, c) => s + c.weight, 0)).toBe(100);
      expect(new Set(brief.rubric.map((c) => c.id)).size).toBe(
        brief.rubric.length,
      );
      for (const c of brief.rubric)
        expect(layerIds.has(c.layerId), `${c.id} → ${c.layerId}`).toBe(true);
    });

    it("has unique requirement ids and four unique twists", () => {
      expect(new Set(brief.requirements.map((r) => r.id)).size).toBe(
        brief.requirements.length,
      );
      expect(brief.twistPool).toHaveLength(4);
      expect(new Set(brief.twistPool.map((t) => t.id)).size).toBe(4);
    });

    it("is never published without a human review", () => {
      expect(["draft", "published"]).toContain(brief.status);
      if (brief.status === "published") expect(brief.reviewed).toBe(true);
    });

    // A newly pasted brief has no layout yet: the other rules still run on it,
    // and its layout is added during review.
    it.skipIf(!LAYOUTS[trackId])(
      "passes every automated check on a correct project layout",
      () => {
        const result = evaluateSubmission({
          repo: {
            id: 1,
            private: false,
            fork: false,
            sizeKb: 100,
            createdAt: new Date("2026-10-05T00:00:00Z"),
          },
          head: { sha: "a", treeSha: "b" },
          stats: {
            count: 20,
            rootCommittedAt: new Date("2026-10-05T00:01:00Z"),
          },
          tree: { truncated: false, paths: LAYOUTS[trackId] },
          firstStartedAt: new Date("2026-10-04T00:00:00Z"),
          repoUsedByOtherUser: false,
          treeSeenFromOtherUser: false,
          requirements: brief.requirements,
        });
        expect(result.checks.filter((c) => !c.passed)).toEqual([]);
      },
    );
  },
);

it("has one brief per track with unique slugs", () => {
  expect(new Set(briefs.map((b) => b.trackId)).size).toBe(briefs.length);
  expect(new Set(briefs.map((b) => b.slug)).size).toBe(briefs.length);
});
