import process from "process";
import dotenv from "dotenv";
dotenv.config({ path: "./backend/.env" });
import connectDB from "../config/db.js";

const resources = [
  // ── BOOKS ─────────────────────────────────────────────────────────────────
  {
    type: "book",
    title: "You Don't Know JS: Async & Performance",
    author: "Kyle Simpson",
    description:
      "Deep dive into JavaScript's async mechanics — callbacks, promises, generators, and the event loop. Required reading before writing any production Node.js code.",
    url: "https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/README.md",
    free_url: "https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/README.md",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["async", "promises", "event-loop", "generators", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Node.js Design Patterns",
    author: "Mario Casciaro & Luciano Mammino",
    description:
      "The definitive guide to scalable, maintainable Node.js architecture. Covers streams, events, creational patterns, structural patterns, and microservices.",
    url: "https://www.nodejsdesignpatterns.com",
    free_url: null,
    is_free: false,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["nodejs", "design-patterns", "streams", "microservices", "architecture"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    description:
      "The engineering bible for backend developers. Covers replication, partitioning, transactions, distributed systems, and stream processing at scale.",
    url: "https://dataintensive.net",
    free_url: null,
    is_free: false,
    difficulty: "advanced",
    paths: ["Backend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["databases", "distributed-systems", "replication", "transactions", "system-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    description:
      "A comprehensive introduction to JavaScript — covering the language from fundamentals through higher-order functions, OOP, and asynchronous programming.",
    url: "https://eloquentjavascript.net",
    free_url: "https://eloquentjavascript.net",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["javascript", "fundamentals", "functions", "oop"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "The Pragmatic Programmer",
    author: "David Thomas & Andrew Hunt",
    description:
      "Career-defining advice for software engineers — DRY, orthogonality, tracer bullets, pragmatic debugging. Applies to every path and every stack.",
    url: "https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition",
    free_url: null,
    is_free: false,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["software-engineering", "best-practices", "career", "debugging"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "High Performance Browser Networking",
    author: "Ilya Grigorik",
    description:
      "How TCP, UDP, TLS, HTTP/1, HTTP/2, WebSocket, and WebRTC actually work — and how to use that knowledge to build faster web apps.",
    url: "https://hpbn.co",
    free_url: "https://hpbn.co",
    is_free: true,
    difficulty: "advanced",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["networking", "http", "tcp", "websocket", "performance"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── DOCUMENTATION ─────────────────────────────────────────────────────────
  {
    type: "documentation",
    title: "Node.js Official Docs — Asynchronous Programming",
    author: "Node.js Contributors",
    description:
      "The canonical reference for Node.js async patterns: callbacks, promises, async/await, the event loop, timers, and the nextTick queue.",
    url: "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick",
    free_url: "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["nodejs", "async", "event-loop", "promises", "timers"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Express.js — Error Handling Guide",
    author: "Express Contributors",
    description:
      "Official guide to synchronous and asynchronous error handling in Express — error middleware, default error handlers, and operational vs programmer errors.",
    url: "https://expressjs.com/en/guide/error-handling.html",
    free_url: "https://expressjs.com/en/guide/error-handling.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["express", "error-handling", "middleware", "nodejs"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Express.js — Routing",
    author: "Express Contributors",
    description:
      "Complete routing reference: route methods, route paths, route parameters, chained handlers, and Express Router for modular route definitions.",
    url: "https://expressjs.com/en/guide/routing.html",
    free_url: "https://expressjs.com/en/guide/routing.html",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["express", "routing", "middleware", "nodejs", "rest"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MongoDB Manual — CRUD Operations",
    author: "MongoDB, Inc.",
    description:
      "Official reference for MongoDB CRUD: insertOne/insertMany, find with filters and projections, updateOne/updateMany with operators, deleteOne/deleteMany.",
    url: "https://www.mongodb.com/docs/manual/crud",
    free_url: "https://www.mongodb.com/docs/manual/crud",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["mongodb", "databases", "crud", "queries", "nosql"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MongoDB Manual — Aggregation Pipeline",
    author: "MongoDB, Inc.",
    description:
      "Master the aggregation framework: $match, $group, $lookup, $project, $sort, $unwind, $facet. The right tool for any analytics or join-like query in MongoDB.",
    url: "https://www.mongodb.com/docs/manual/aggregation",
    free_url: "https://www.mongodb.com/docs/manual/aggregation",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["mongodb", "aggregation", "databases", "queries", "pipelines"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MDN — HTTP Status Codes",
    author: "Mozilla Contributors",
    description:
      "Complete reference for HTTP response status codes — 1xx informational, 2xx success, 3xx redirection, 4xx client errors, 5xx server errors.",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
    free_url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["http", "rest", "api-design", "networking"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "JWT.io — Introduction to JSON Web Tokens",
    author: "Auth0",
    description:
      "Explains JWT structure, signing algorithms (HS256/RS256), validation, and common attack vectors. Essential before implementing any token-based auth.",
    url: "https://jwt.io/introduction",
    free_url: "https://jwt.io/introduction",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["auth", "jwt", "security", "tokens"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── GUIDES ────────────────────────────────────────────────────────────────
  {
    type: "guide",
    title: "REST API Design Best Practices",
    author: "Phil Sturgeon",
    description:
      "Practical guide to designing clean REST APIs: naming conventions, versioning strategies, pagination, error response shapes, and HATEOAS basics.",
    url: "https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api",
    free_url: "https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["rest", "api-design", "http", "versioning", "pagination"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "Node.js Best Practices",
    author: "Yoni Goldberg",
    description:
      "The most comprehensive Node.js best practices list — project structure, error handling, testing, security, production readiness, and Docker practices.",
    url: "https://github.com/goldbergyoni/nodebestpractices",
    free_url: "https://github.com/goldbergyoni/nodebestpractices",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["nodejs", "best-practices", "architecture", "security", "testing"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "The Twelve-Factor App",
    author: "Adam Wiggins",
    description:
      "Methodology for building SaaS apps: codebase, dependencies, config, backing services, build/release/run, processes, port binding, concurrency, and more.",
    url: "https://12factor.net",
    free_url: "https://12factor.net",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["architecture", "devops", "deployment", "configuration", "saas"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── CHEATSHEETS ───────────────────────────────────────────────────────────
  {
    type: "cheatsheet",
    title: "HTTP Status Codes Cheatsheet",
    author: "devhints.io",
    description:
      "Quick-reference for every HTTP status code grouped by category with descriptions and when to use each one in your API responses.",
    url: "https://devhints.io/http-status",
    free_url: "https://devhints.io/http-status",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["http", "rest", "api-design", "status-codes"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Big-O Complexity Cheatsheet",
    author: "bigocheatsheet.com",
    description:
      "Time and space complexity of every common data structure and algorithm — arrays, linked lists, trees, heaps, sorting algorithms, and graph operations.",
    url: "https://www.bigocheatsheet.com",
    free_url: "https://www.bigocheatsheet.com",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["algorithms", "data-structures", "complexity", "computer-science"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "MongoDB Query Operators Cheatsheet",
    author: "devhints.io",
    description:
      "Quick reference for MongoDB query operators: $eq, $gt, $in, $regex, $exists, logical operators, array operators, and update operators.",
    url: "https://devhints.io/mongodb",
    free_url: "https://devhints.io/mongodb",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["mongodb", "databases", "queries", "nosql"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Express.js Cheatsheet",
    author: "devhints.io",
    description:
      "At-a-glance reference for Express — app methods, router methods, request/response objects, middleware patterns, and common configuration.",
    url: "https://devhints.io/express",
    free_url: "https://devhints.io/express",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["express", "nodejs", "middleware", "routing"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seed() {
  const db = await connectDB();
  const col = db.collection("libraryResources");

  // Create text index for full-text search on first run
  await col.createIndex(
    { title: "text", description: "text", topics: "text" },
    { name: "library_text_search" }
  );

  // Remove previous seed data (idempotent re-runs)
  await col.deleteMany({});
  console.log("Cleared existing library resources.");

  const result = await col.insertMany(resources);
  console.log(`Seeded ${result.insertedCount} library resources into 'libraryResources' collection.`);

  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
