import process from "process";
import dotenv from "dotenv";
dotenv.config({ path: "./backend/.env" });
import connectDB from "../config/db.js";

const resources = [

  // ════════════════════════════════════════════════════════════
  // BOOKS
  // ════════════════════════════════════════════════════════════

  // ── Backend / Full Stack ─────────────────────────────────────
  {
    type: "book",
    title: "You Don't Know JS: Async & Performance",
    author: "Kyle Simpson",
    description:
      "Deep dive into JavaScript's async mechanics — callbacks, promises, generators, and the event loop. Required reading before writing any production Node.js code.",
    url: "https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/README.md",
    free_url: "https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/README.md",
    is_free: true,
    pages: 296,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["async", "promises", "event-loop", "generators", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "You Don't Know JS: Scope & Closures",
    author: "Kyle Simpson",
    description:
      "Explains how JavaScript's scope, hoisting, closures, and the module pattern actually work under the hood. Eliminates the most common JS misconceptions.",
    url: "https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/README.md",
    free_url: "https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/README.md",
    is_free: true,
    pages: 242,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["javascript", "scope", "closures", "hoisting", "modules"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Node.js Design Patterns",
    author: "Mario Casciaro & Luciano Mammino",
    description:
      "The definitive guide to scalable, maintainable Node.js architecture. Covers streams, events, creational patterns, structural patterns, and microservices.",
    url: "https://www.nodejsdesignpatterns.com",
    free_url: null,
    is_free: false,
    pages: 660,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["nodejs", "design-patterns", "streams", "microservices", "architecture"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    description:
      "The engineering bible for backend developers. Covers replication, partitioning, transactions, distributed systems, and stream processing at scale.",
    url: "https://dataintensive.net",
    free_url: null,
    is_free: false,
    pages: 611,
    difficulty: "advanced",
    paths: ["Backend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["databases", "distributed-systems", "replication", "transactions", "system-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Clean Code",
    author: "Robert C. Martin",
    description:
      "Timeless principles for writing readable, maintainable code — meaningful names, small functions, error handling, unit tests, and refactoring techniques.",
    url: "https://www.oreilly.com/library/view/clean-code-a/9780136083238",
    free_url: null,
    is_free: false,
    pages: 431,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer", "QA Engineer"],
    layer_ids: [],
    topics: ["software-engineering", "refactoring", "clean-code", "best-practices"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Clean Architecture",
    author: "Robert C. Martin",
    description:
      "Principles for structuring software systems — dependency rule, SOLID principles, component cohesion, and architectural boundaries that survive changing requirements.",
    url: "https://www.oreilly.com/library/view/clean-architecture-a/9780134494272",
    free_url: null,
    is_free: false,
    pages: 432,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["architecture", "solid", "design-patterns", "software-engineering"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    description:
      "A comprehensive introduction to JavaScript — covering the language from fundamentals through higher-order functions, OOP, and asynchronous programming.",
    url: "https://eloquentjavascript.net",
    free_url: "https://eloquentjavascript.net",
    is_free: true,
    pages: 472,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["javascript", "fundamentals", "functions", "oop"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "The Pragmatic Programmer",
    author: "David Thomas & Andrew Hunt",
    description:
      "Career-defining advice for software engineers — DRY, orthogonality, tracer bullets, pragmatic debugging. Applies to every path and every stack.",
    url: "https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition",
    free_url: null,
    is_free: false,
    pages: 352,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer", "DevOps", "QA Engineer"],
    layer_ids: [],
    topics: ["software-engineering", "best-practices", "career", "debugging"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "High Performance Browser Networking",
    author: "Ilya Grigorik",
    description:
      "How TCP, UDP, TLS, HTTP/1, HTTP/2, WebSocket, and WebRTC actually work — and how to use that knowledge to build faster web apps.",
    url: "https://hpbn.co",
    free_url: "https://hpbn.co",
    is_free: true,
    pages: 400,
    difficulty: "advanced",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["networking", "http", "tcp", "websocket", "performance"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Frontend ─────────────────────────────────────────────────
  {
    type: "book",
    title: "CSS: The Definitive Guide",
    author: "Eric Meyer & Estelle Weyl",
    description:
      "The most complete reference for CSS — the box model, selectors, typography, colors, layout with Flexbox and Grid, transforms, animations, and more.",
    url: "https://www.oreilly.com/library/view/css-the-definitive/9781098117603",
    free_url: null,
    is_free: false,
    pages: 1090,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["css", "flexbox", "grid", "layout", "animations"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Learning React",
    author: "Alex Banks & Eve Porcello",
    description:
      "Practical guide to modern React — functional components, hooks, context, state management, and building real-world applications with a component-driven mindset.",
    url: "https://www.oreilly.com/library/view/learning-react-2nd/9781492051718",
    free_url: null,
    is_free: false,
    pages: 310,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["react", "hooks", "components", "state-management", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    description:
      "A short, opinionated guide to the best features of JavaScript — functions, objects, and patterns that make the language genuinely powerful once you know where to look.",
    url: "https://www.oreilly.com/library/view/javascript-the-good/9780596517748",
    free_url: null,
    is_free: false,
    pages: 176,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer", "Backend Developer"],
    layer_ids: [],
    topics: ["javascript", "fundamentals", "functions", "patterns"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── AI & ML ──────────────────────────────────────────────────
  {
    type: "book",
    title: "Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow",
    author: "Aurélien Géron",
    description:
      "The most practical ML book available — covers the full pipeline from data prep and feature engineering through SVMs, decision trees, neural networks, and deep learning.",
    url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967",
    free_url: null,
    is_free: false,
    pages: 851,
    difficulty: "intermediate",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["machine-learning", "scikit-learn", "tensorflow", "keras", "deep-learning", "python"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Deep Learning",
    author: "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
    description:
      "The authoritative textbook on deep learning — linear algebra, probability, neural network architectures, CNNs, RNNs, optimization, and regularization.",
    url: "https://www.deeplearningbook.org",
    free_url: "https://www.deeplearningbook.org",
    is_free: true,
    pages: 800,
    difficulty: "advanced",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["deep-learning", "neural-networks", "cnn", "rnn", "optimization", "mathematics"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Python for Data Analysis",
    author: "Wes McKinney",
    description:
      "Written by the creator of pandas — covers NumPy, pandas, data cleaning, time series, and matplotlib. The essential toolkit for any data-focused ML practitioner.",
    url: "https://www.oreilly.com/library/view/python-for-data/9781098104023",
    free_url: null,
    is_free: false,
    pages: 579,
    difficulty: "beginner",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["python", "pandas", "numpy", "data-analysis", "data-cleaning"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Natural Language Processing with Transformers",
    author: "Lewis Tunstall, Leandro von Werra & Thomas Wolf",
    description:
      "Practical guide to building NLP applications with Hugging Face Transformers — fine-tuning, text classification, NER, summarization, and question answering.",
    url: "https://www.oreilly.com/library/view/natural-language-processing/9781098136789",
    free_url: null,
    is_free: false,
    pages: 396,
    difficulty: "intermediate",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["nlp", "transformers", "hugging-face", "bert", "llm", "python"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── DevOps ───────────────────────────────────────────────────
  {
    type: "book",
    title: "The Phoenix Project",
    author: "Gene Kim, Kevin Behr & George Spafford",
    description:
      "A novel about DevOps transformation — explains the Three Ways, flow, feedback, and continuous learning through a story that engineers actually remember.",
    url: "https://itrevolution.com/the-phoenix-project",
    free_url: null,
    is_free: false,
    pages: 432,
    difficulty: "beginner",
    paths: ["DevOps"],
    layer_ids: [],
    topics: ["devops", "ci-cd", "culture", "flow", "lean"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Site Reliability Engineering",
    author: "Google SRE Team",
    description:
      "How Google runs production — SLOs, error budgets, toil reduction, incident response, postmortems, and the organizational model behind reliable large-scale systems.",
    url: "https://sre.google/sre-book/table-of-contents",
    free_url: "https://sre.google/sre-book/table-of-contents",
    is_free: true,
    pages: 552,
    difficulty: "advanced",
    paths: ["DevOps", "Backend Developer"],
    layer_ids: [],
    topics: ["sre", "reliability", "slo", "incident-response", "monitoring", "on-call"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Docker Deep Dive",
    author: "Nigel Poulton",
    description:
      "The fastest way to understand Docker — images, containers, volumes, networking, Compose, and Swarm. Short, dense, and zero fluff.",
    url: "https://www.nigelpoulton.com/books",
    free_url: null,
    is_free: false,
    pages: 208,
    difficulty: "beginner",
    paths: ["DevOps", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["docker", "containers", "devops", "deployment", "compose"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Kubernetes in Action",
    author: "Marko Lukša",
    description:
      "Comprehensive guide to Kubernetes — pods, deployments, services, config maps, persistent volumes, RBAC, and operating clusters in production.",
    url: "https://www.manning.com/books/kubernetes-in-action-second-edition",
    free_url: null,
    is_free: false,
    pages: 712,
    difficulty: "intermediate",
    paths: ["DevOps"],
    layer_ids: [],
    topics: ["kubernetes", "containers", "devops", "orchestration", "cloud"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Mobile ───────────────────────────────────────────────────
  {
    type: "book",
    title: "iOS Programming: The Big Nerd Ranch Guide",
    author: "Christian Keur & Aaron Hillegass",
    description:
      "The standard iOS dev textbook — Swift fundamentals, UIKit, view controllers, table views, networking, persistence, and Auto Layout from the ground up.",
    url: "https://www.bignerdranch.com/books/ios-programming-the-big-nerd-ranch-guide-7th-edition",
    free_url: null,
    is_free: false,
    pages: 536,
    difficulty: "beginner",
    paths: ["Mobile Developer"],
    layer_ids: [],
    topics: ["ios", "swift", "uikit", "xcode", "mobile"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "React Native in Action",
    author: "Nader Dabit",
    description:
      "Build cross-platform mobile apps with React Native — components, navigation, animations, camera, location, push notifications, and publishing to both stores.",
    url: "https://www.manning.com/books/react-native-in-action",
    free_url: null,
    is_free: false,
    pages: 312,
    difficulty: "intermediate",
    paths: ["Mobile Developer", "Frontend Developer"],
    layer_ids: [],
    topics: ["react-native", "mobile", "cross-platform", "javascript", "ios", "android"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Game Developer ───────────────────────────────────────────
  {
    type: "book",
    title: "Game Programming Patterns",
    author: "Robert Nystrom",
    description:
      "Gang of Four design patterns applied to game development — command, flyweight, observer, prototype, state, component, event queue, and service locator.",
    url: "https://gameprogrammingpatterns.com",
    free_url: "https://gameprogrammingpatterns.com",
    is_free: true,
    pages: 345,
    difficulty: "intermediate",
    paths: ["Game Developer"],
    layer_ids: [],
    topics: ["game-dev", "design-patterns", "architecture", "c++", "unity"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Real-Time Rendering",
    author: "Tomas Akenine-Möller, Eric Haines & Naty Hoffman",
    description:
      "The definitive reference for real-time 3D graphics — rasterization, shaders, texturing, shadows, global illumination, and GPU pipeline optimization.",
    url: "https://www.realtimerendering.com",
    free_url: null,
    is_free: false,
    pages: 1138,
    difficulty: "advanced",
    paths: ["Game Developer"],
    layer_ids: [],
    topics: ["graphics", "rendering", "shaders", "opengl", "gpu", "3d"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "Introduction to Game Design, Prototyping, and Development",
    author: "Jeremy Gibson Bond",
    description:
      "Covers the full game creation workflow in Unity — design principles, C# scripting, physics, UI, audio, and shipping a finished game.",
    url: "https://www.pearson.com/en-us/subject-catalog/p/introduction-to-game-design-prototyping-and-development/P200000004843",
    free_url: null,
    is_free: false,
    pages: 720,
    difficulty: "beginner",
    paths: ["Game Developer"],
    layer_ids: [],
    topics: ["unity", "game-design", "c-sharp", "prototyping", "game-dev"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── QA Engineer ──────────────────────────────────────────────
  {
    type: "book",
    title: "Agile Testing",
    author: "Lisa Crispin & Janet Gregory",
    description:
      "How QA fits into agile teams — the testing quadrants model, whole-team quality, exploratory testing, test automation strategy, and continuous feedback loops.",
    url: "https://www.pearson.com/en-us/subject-catalog/p/agile-testing-a-practical-guide-for-testers-and-agile-teams/P200000004348",
    free_url: null,
    is_free: false,
    pages: 576,
    difficulty: "beginner",
    paths: ["QA Engineer"],
    layer_ids: [],
    topics: ["testing", "agile", "qa", "test-strategy", "automation"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "book",
    title: "The Art of Software Testing",
    author: "Glenford J. Myers",
    description:
      "The classic text on software testing — black-box testing, white-box testing, code inspections, debugging, and building an effective test strategy from first principles.",
    url: "https://www.wiley.com/en-us/The+Art+of+Software+Testing%2C+3rd+Edition-p-9781118031964",
    free_url: null,
    is_free: false,
    pages: 240,
    difficulty: "intermediate",
    paths: ["QA Engineer"],
    layer_ids: [],
    topics: ["testing", "qa", "black-box", "white-box", "test-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ════════════════════════════════════════════════════════════
  // DOCUMENTATION
  // ════════════════════════════════════════════════════════════

  // ── Backend / Node ───────────────────────────────────────────
  {
    type: "documentation",
    title: "Node.js Official Docs — Asynchronous Programming",
    author: "Node.js Contributors",
    description:
      "The canonical reference for Node.js async patterns: callbacks, promises, async/await, the event loop, timers, and the nextTick queue.",
    url: "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick",
    free_url: "https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["nodejs", "async", "event-loop", "promises", "timers"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Express.js — Error Handling Guide",
    author: "Express Contributors",
    description:
      "Official guide to synchronous and asynchronous error handling in Express — error middleware, default error handlers, and operational vs programmer errors.",
    url: "https://expressjs.com/en/guide/error-handling.html",
    free_url: "https://expressjs.com/en/guide/error-handling.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["express", "error-handling", "middleware", "nodejs"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Express.js — Routing",
    author: "Express Contributors",
    description:
      "Complete routing reference: route methods, route paths, route parameters, chained handlers, and Express Router for modular route definitions.",
    url: "https://expressjs.com/en/guide/routing.html",
    free_url: "https://expressjs.com/en/guide/routing.html",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["express", "routing", "middleware", "nodejs", "rest"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MongoDB Manual — CRUD Operations",
    author: "MongoDB, Inc.",
    description:
      "Official reference for MongoDB CRUD: insertOne/insertMany, find with filters and projections, updateOne/updateMany with operators, deleteOne/deleteMany.",
    url: "https://www.mongodb.com/docs/manual/crud",
    free_url: "https://www.mongodb.com/docs/manual/crud",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["mongodb", "databases", "crud", "queries", "nosql"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MongoDB Manual — Aggregation Pipeline",
    author: "MongoDB, Inc.",
    description:
      "Master the aggregation framework: $match, $group, $lookup, $project, $sort, $unwind, $facet. The right tool for any analytics or join-like query in MongoDB.",
    url: "https://www.mongodb.com/docs/manual/aggregation",
    free_url: "https://www.mongodb.com/docs/manual/aggregation",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["mongodb", "aggregation", "databases", "queries", "pipelines"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MDN — HTTP Status Codes",
    author: "Mozilla Contributors",
    description:
      "Complete reference for HTTP response status codes — 1xx informational, 2xx success, 3xx redirection, 4xx client errors, 5xx server errors.",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
    free_url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["http", "rest", "api-design", "networking"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "JWT.io — Introduction to JSON Web Tokens",
    author: "Auth0",
    description:
      "Explains JWT structure, signing algorithms (HS256/RS256), validation, and common attack vectors. Essential before implementing any token-based auth.",
    url: "https://jwt.io/introduction",
    free_url: "https://jwt.io/introduction",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["auth", "jwt", "security", "tokens"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Redis Documentation — Data Types",
    author: "Redis, Inc.",
    description:
      "Official reference for Redis data types — strings, lists, sets, sorted sets, hashes, streams, and bitmaps. Covers use cases and time complexity for every operation.",
    url: "https://redis.io/docs/data-types",
    free_url: "https://redis.io/docs/data-types",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["redis", "caching", "data-structures", "pub-sub", "queues"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Frontend ─────────────────────────────────────────────────
  {
    type: "documentation",
    title: "MDN — CSS Flexbox",
    author: "Mozilla Contributors",
    description:
      "The complete reference for CSS Flexbox — flex containers, flex items, alignment, wrapping, ordering, and responsive layout patterns with live examples.",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout",
    free_url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout",
    is_free: true,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["css", "flexbox", "layout", "responsive-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "MDN — CSS Grid Layout",
    author: "Mozilla Contributors",
    description:
      "Reference for CSS Grid — grid containers, tracks, lines, areas, auto placement, explicit vs implicit grids, and alignment across two axes.",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout",
    free_url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["css", "grid", "layout", "responsive-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "React Official Docs",
    author: "Meta Open Source",
    description:
      "The official React docs rewritten in 2023 — covers components, hooks (useState, useEffect, useContext, useReducer, useRef), Suspense, and concurrent features.",
    url: "https://react.dev",
    free_url: "https://react.dev",
    is_free: true,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["react", "hooks", "components", "jsx", "state-management"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "TypeScript Handbook",
    author: "Microsoft",
    description:
      "Official TypeScript guide — types, interfaces, generics, enums, type narrowing, utility types, and module patterns. Essential for typed JavaScript development.",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    free_url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["typescript", "types", "generics", "interfaces", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Vite — Getting Started",
    author: "Vite Contributors",
    description:
      "Official Vite docs — project setup, hot module replacement, plugins, environment variables, static assets, build optimization, and deployment.",
    url: "https://vitejs.dev/guide",
    free_url: "https://vitejs.dev/guide",
    is_free: true,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["vite", "bundler", "build-tools", "hmr", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── AI & ML ──────────────────────────────────────────────────
  {
    type: "documentation",
    title: "scikit-learn User Guide",
    author: "scikit-learn Contributors",
    description:
      "The complete reference for scikit-learn — supervised and unsupervised algorithms, preprocessing, pipelines, model evaluation, and cross-validation.",
    url: "https://scikit-learn.org/stable/user_guide.html",
    free_url: "https://scikit-learn.org/stable/user_guide.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["machine-learning", "scikit-learn", "python", "classification", "regression", "clustering"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "PyTorch Documentation",
    author: "Meta AI",
    description:
      "Official PyTorch docs — tensors, autograd, neural network modules, optimizers, data loading, and deployment. The primary framework for research-grade deep learning.",
    url: "https://pytorch.org/docs/stable/index.html",
    free_url: "https://pytorch.org/docs/stable/index.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["pytorch", "deep-learning", "tensors", "autograd", "neural-networks", "python"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Hugging Face — Transformers Docs",
    author: "Hugging Face",
    description:
      "How to use and fine-tune pre-trained transformer models — BERT, GPT-2, T5, Llama. Covers pipelines, tokenizers, model hubs, and training with Trainer API.",
    url: "https://huggingface.co/docs/transformers/index",
    free_url: "https://huggingface.co/docs/transformers/index",
    is_free: true,
    difficulty: "intermediate",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["transformers", "nlp", "bert", "gpt", "fine-tuning", "hugging-face"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "NumPy Documentation",
    author: "NumPy Contributors",
    description:
      "Official NumPy reference — array creation, indexing, slicing, broadcasting, linear algebra, random sampling, and integration with the broader scientific Python ecosystem.",
    url: "https://numpy.org/doc/stable/user/index.html",
    free_url: "https://numpy.org/doc/stable/user/index.html",
    is_free: true,
    difficulty: "beginner",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["numpy", "arrays", "linear-algebra", "python", "data-science"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── DevOps ───────────────────────────────────────────────────
  {
    type: "documentation",
    title: "Docker Official Docs",
    author: "Docker, Inc.",
    description:
      "Official Docker docs — building images with Dockerfile, running containers, volumes, networking, Docker Compose, and multi-stage builds for production.",
    url: "https://docs.docker.com",
    free_url: "https://docs.docker.com",
    is_free: true,
    difficulty: "beginner",
    paths: ["DevOps", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["docker", "containers", "dockerfile", "compose", "devops"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Kubernetes Official Docs",
    author: "CNCF / Kubernetes Contributors",
    description:
      "Kubernetes concepts and reference — pods, deployments, services, ingress, config maps, secrets, RBAC, namespaces, and cluster administration.",
    url: "https://kubernetes.io/docs/home",
    free_url: "https://kubernetes.io/docs/home",
    is_free: true,
    difficulty: "intermediate",
    paths: ["DevOps"],
    layer_ids: [],
    topics: ["kubernetes", "k8s", "containers", "orchestration", "devops", "cloud"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "GitHub Actions Documentation",
    author: "GitHub",
    description:
      "Build CI/CD pipelines with GitHub Actions — workflows, triggers, jobs, steps, runners, secrets, matrix builds, reusable workflows, and marketplace actions.",
    url: "https://docs.github.com/en/actions",
    free_url: "https://docs.github.com/en/actions",
    is_free: true,
    difficulty: "intermediate",
    paths: ["DevOps", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["ci-cd", "github-actions", "automation", "devops", "pipelines"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Terraform Documentation",
    author: "HashiCorp",
    description:
      "Infrastructure as code with Terraform — providers, resources, variables, outputs, state management, modules, and deploying to AWS/GCP/Azure.",
    url: "https://developer.hashicorp.com/terraform/docs",
    free_url: "https://developer.hashicorp.com/terraform/docs",
    is_free: true,
    difficulty: "intermediate",
    paths: ["DevOps"],
    layer_ids: [],
    topics: ["terraform", "iac", "infrastructure", "cloud", "devops", "aws"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Mobile ───────────────────────────────────────────────────
  {
    type: "documentation",
    title: "React Native Official Docs",
    author: "Meta Open Source",
    description:
      "Build mobile apps with React Native — core components, navigation, styling, animations, device APIs (camera, location, notifications), and publishing to App Store and Play Store.",
    url: "https://reactnative.dev/docs/getting-started",
    free_url: "https://reactnative.dev/docs/getting-started",
    is_free: true,
    difficulty: "beginner",
    paths: ["Mobile Developer", "Frontend Developer"],
    layer_ids: [],
    topics: ["react-native", "mobile", "ios", "android", "javascript", "cross-platform"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Swift Language Guide",
    author: "Apple",
    description:
      "Official Swift reference — syntax, types, optionals, closures, enumerations, structures, classes, protocols, generics, and concurrency with async/await.",
    url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language",
    free_url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language",
    is_free: true,
    difficulty: "beginner",
    paths: ["Mobile Developer"],
    layer_ids: [],
    topics: ["swift", "ios", "apple", "optionals", "protocols", "concurrency"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Game Developer ───────────────────────────────────────────
  {
    type: "documentation",
    title: "Unity Manual",
    author: "Unity Technologies",
    description:
      "The official Unity reference — GameObjects, components, the physics engine, input system, UI Toolkit, animation, audio, lighting, and build settings.",
    url: "https://docs.unity3d.com/Manual/index.html",
    free_url: "https://docs.unity3d.com/Manual/index.html",
    is_free: true,
    difficulty: "beginner",
    paths: ["Game Developer"],
    layer_ids: [],
    topics: ["unity", "game-dev", "c-sharp", "physics", "animation", "ui"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Godot Engine Docs",
    author: "Godot Contributors",
    description:
      "Official Godot docs — the scene system, GDScript, nodes and signals, 2D and 3D physics, shaders, export, and the open-source game engine workflow.",
    url: "https://docs.godotengine.org/en/stable",
    free_url: "https://docs.godotengine.org/en/stable",
    is_free: true,
    difficulty: "beginner",
    paths: ["Game Developer"],
    layer_ids: [],
    topics: ["godot", "game-dev", "gdscript", "2d", "3d", "open-source"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── QA Engineer ──────────────────────────────────────────────
  {
    type: "documentation",
    title: "Playwright Documentation",
    author: "Microsoft",
    description:
      "Official Playwright reference — browser automation, page interactions, assertions, fixtures, API testing, visual comparisons, and CI integration.",
    url: "https://playwright.dev/docs/intro",
    free_url: "https://playwright.dev/docs/intro",
    is_free: true,
    difficulty: "intermediate",
    paths: ["QA Engineer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["playwright", "e2e-testing", "automation", "browsers", "qa"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Jest Documentation",
    author: "Meta Open Source",
    description:
      "Official Jest reference — test runners, matchers, mocking, spies, timers, snapshots, code coverage, and testing async code in JavaScript/TypeScript projects.",
    url: "https://jestjs.io/docs/getting-started",
    free_url: "https://jestjs.io/docs/getting-started",
    is_free: true,
    difficulty: "beginner",
    paths: ["QA Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["jest", "unit-testing", "mocking", "coverage", "javascript", "testing"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "documentation",
    title: "Cypress Documentation",
    author: "Cypress.io",
    description:
      "Official Cypress reference — end-to-end testing in the browser, commands, assertions, network stubbing, component testing, and visual regression.",
    url: "https://docs.cypress.io",
    free_url: "https://docs.cypress.io",
    is_free: true,
    difficulty: "beginner",
    paths: ["QA Engineer", "Frontend Developer"],
    layer_ids: [],
    topics: ["cypress", "e2e-testing", "qa", "automation", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ════════════════════════════════════════════════════════════
  // GUIDES
  // ════════════════════════════════════════════════════════════

  // ── Backend / Full Stack ─────────────────────────────────────
  {
    type: "guide",
    title: "REST API Design Best Practices",
    author: "Vinay Sahni",
    description:
      "Practical guide to designing clean REST APIs: naming conventions, versioning strategies, pagination, error response shapes, and HATEOAS basics.",
    url: "https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api",
    free_url: "https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["rest", "api-design", "http", "versioning", "pagination"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "Node.js Best Practices",
    author: "Yoni Goldberg",
    description:
      "The most comprehensive Node.js best practices list — project structure, error handling, testing, security, production readiness, and Docker practices.",
    url: "https://github.com/goldbergyoni/nodebestpractices",
    free_url: "https://github.com/goldbergyoni/nodebestpractices",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["nodejs", "best-practices", "architecture", "security", "testing"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "The Twelve-Factor App",
    author: "Adam Wiggins",
    description:
      "Methodology for building SaaS apps: codebase, dependencies, config, backing services, build/release/run, processes, port binding, concurrency, and more.",
    url: "https://12factor.net",
    free_url: "https://12factor.net",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["architecture", "devops", "deployment", "configuration", "saas"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "How HTTPS Works",
    author: "How HTTPS Works",
    description:
      "A visual, comic-style walkthrough of TLS — certificate authorities, handshake protocol, symmetric vs asymmetric encryption, and why HTTPS protects you.",
    url: "https://howhttps.works",
    free_url: "https://howhttps.works",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer", "DevOps"],
    layer_ids: [],
    topics: ["https", "tls", "security", "encryption", "networking"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "OWASP Top 10",
    author: "OWASP Foundation",
    description:
      "The definitive list of the 10 most critical web application security risks — injection, broken auth, XSS, IDOR, SSRF, and more. Required reading for any backend developer.",
    url: "https://owasp.org/www-project-top-ten",
    free_url: "https://owasp.org/www-project-top-ten",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Full Stack Developer", "QA Engineer"],
    layer_ids: [],
    topics: ["security", "owasp", "xss", "injection", "auth", "web"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── Frontend ─────────────────────────────────────────────────
  {
    type: "guide",
    title: "A Complete Guide to Flexbox",
    author: "CSS-Tricks (Chris Coyier)",
    description:
      "The most-referenced visual guide to CSS Flexbox — every property explained for both flex container and flex items with live diagrams.",
    url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox",
    free_url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox",
    is_free: true,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["css", "flexbox", "layout", "responsive-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "A Complete Guide to CSS Grid",
    author: "CSS-Tricks (Chris House)",
    description:
      "Visual reference for every CSS Grid property — grid-template-columns, grid-area, auto-placement, named lines, and responsive two-dimensional layouts.",
    url: "https://css-tricks.com/snippets/css/complete-guide-grid",
    free_url: "https://css-tricks.com/snippets/css/complete-guide-grid",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["css", "grid", "layout", "responsive-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "JavaScript Event Loop Explained",
    author: "Jake Archibald",
    description:
      "In-depth visual walkthrough of the JS event loop — call stack, task queue, microtask queue, requestAnimationFrame, and why order of execution matters.",
    url: "https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules",
    free_url: "https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["javascript", "event-loop", "async", "microtasks", "promises"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "Web Accessibility (a11y) Guide",
    author: "WebAIM",
    description:
      "Practical guide to making web apps accessible — semantic HTML, ARIA roles, keyboard navigation, color contrast, screen reader testing, and WCAG compliance.",
    url: "https://webaim.org/intro",
    free_url: "https://webaim.org/intro",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["accessibility", "a11y", "aria", "wcag", "semantic-html", "ux"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── AI & ML ──────────────────────────────────────────────────
  {
    type: "guide",
    title: "Andrej Karpathy — Neural Networks: Zero to Hero",
    author: "Andrej Karpathy",
    description:
      "Ground-up implementation of neural networks — backpropagation from scratch, building micrograd, makemore, and a GPT-2 level language model. Best free ML education available.",
    url: "https://karpathy.ai/zero-to-hero.html",
    free_url: "https://karpathy.ai/zero-to-hero.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["neural-networks", "backpropagation", "gpt", "llm", "python", "deep-learning"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "Attention Is All You Need — Paper Explained",
    author: "Yannic Kilcher",
    description:
      "Clear walkthrough of the original transformer paper — self-attention, multi-head attention, positional encoding, and why this architecture changed everything in NLP and beyond.",
    url: "https://www.youtube.com/watch?v=iDulhoQ2pro",
    free_url: "https://www.youtube.com/watch?v=iDulhoQ2pro",
    is_free: true,
    difficulty: "advanced",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["transformers", "attention", "nlp", "deep-learning", "research"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "ML System Design Guide",
    author: "Chip Huyen",
    description:
      "How to design production ML systems — data pipelines, feature engineering, training vs serving infrastructure, monitoring, and retraining strategies at scale.",
    url: "https://huyenchip.com/machine-learning-systems-design/toc.html",
    free_url: "https://huyenchip.com/machine-learning-systems-design/toc.html",
    is_free: true,
    difficulty: "advanced",
    paths: ["AI & ML"],
    layer_ids: [],
    topics: ["ml-systems", "data-pipelines", "feature-engineering", "mlops", "system-design"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── DevOps ───────────────────────────────────────────────────
  {
    type: "guide",
    title: "Docker Best Practices for Production",
    author: "Snyk",
    description:
      "10 best practices for writing production Dockerfiles — non-root users, multi-stage builds, .dockerignore, minimal base images, layer caching, and security scanning.",
    url: "https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker",
    free_url: "https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker",
    is_free: true,
    difficulty: "intermediate",
    paths: ["DevOps", "Backend Developer"],
    layer_ids: [],
    topics: ["docker", "containers", "security", "production", "devops"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "CI/CD Pipeline Best Practices",
    author: "Atlassian",
    description:
      "How to design a reliable CI/CD pipeline — branching strategies, automated testing stages, deployment environments, rollback strategies, and feature flags.",
    url: "https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment",
    free_url: "https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment",
    is_free: true,
    difficulty: "intermediate",
    paths: ["DevOps", "Backend Developer"],
    layer_ids: [],
    topics: ["ci-cd", "pipelines", "automation", "devops", "deployment"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── QA Engineer ──────────────────────────────────────────────
  {
    type: "guide",
    title: "Testing JavaScript — Kent C. Dodds",
    author: "Kent C. Dodds",
    description:
      "The philosophy behind effective JS testing — the testing trophy, avoiding implementation details, testing user behavior, and when to unit vs integration vs e2e test.",
    url: "https://testingjavascript.com",
    free_url: null,
    is_free: false,
    difficulty: "intermediate",
    paths: ["QA Engineer", "Frontend Developer", "Backend Developer"],
    layer_ids: [],
    topics: ["testing", "jest", "react-testing-library", "e2e", "philosophy"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "guide",
    title: "Google Testing Blog — Test Sizes",
    author: "Google Engineering",
    description:
      "Google's internal framework for categorizing tests by size (small/medium/large) — execution time, flakiness, hermetic isolation, and why test size matters more than type.",
    url: "https://testing.googleblog.com/2010/12/test-sizes.html",
    free_url: "https://testing.googleblog.com/2010/12/test-sizes.html",
    is_free: true,
    difficulty: "intermediate",
    paths: ["QA Engineer"],
    layer_ids: [],
    topics: ["testing", "qa", "test-strategy", "unit-testing", "integration-testing"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ════════════════════════════════════════════════════════════
  // CHEATSHEETS
  // ════════════════════════════════════════════════════════════

  {
    type: "cheatsheet",
    title: "HTTP Status Codes Cheatsheet",
    author: "devhints.io",
    description:
      "Quick-reference for every HTTP status code grouped by category with descriptions and when to use each one in your API responses.",
    url: "https://devhints.io/http-status",
    free_url: "https://devhints.io/http-status",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["http", "rest", "api-design", "status-codes"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Big-O Complexity Cheatsheet",
    author: "bigocheatsheet.com",
    description:
      "Time and space complexity of every common data structure and algorithm — arrays, linked lists, trees, heaps, sorting algorithms, and graph operations.",
    url: "https://www.bigocheatsheet.com",
    free_url: "https://www.bigocheatsheet.com",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["algorithms", "data-structures", "complexity", "computer-science"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "MongoDB Query Operators Cheatsheet",
    author: "devhints.io",
    description:
      "Quick reference for MongoDB query operators: $eq, $gt, $in, $regex, $exists, logical operators, array operators, and update operators.",
    url: "https://devhints.io/mongodb",
    free_url: "https://devhints.io/mongodb",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["mongodb", "databases", "queries", "nosql"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Express.js Cheatsheet",
    author: "devhints.io",
    description:
      "At-a-glance reference for Express — app methods, router methods, request/response objects, middleware patterns, and common configuration.",
    url: "https://devhints.io/express",
    free_url: "https://devhints.io/express",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["express", "nodejs", "middleware", "routing"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Git Cheatsheet",
    author: "GitHub",
    description:
      "Every Git command you actually use — init, clone, branch, checkout, merge, rebase, stash, cherry-pick, reset, revert, and remote operations.",
    url: "https://education.github.com/git-cheat-sheet-education.pdf",
    free_url: "https://education.github.com/git-cheat-sheet-education.pdf",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer", "DevOps", "Mobile Developer", "Game Developer", "QA Engineer", "AI & ML"],
    layer_ids: [],
    topics: ["git", "version-control", "github", "branching", "workflow"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "SQL Cheatsheet",
    author: "LearnSQL.com",
    description:
      "Quick reference for SQL — SELECT with filtering/sorting/joins, GROUP BY with aggregates, subqueries, CTEs, window functions, INSERT/UPDATE/DELETE, and index basics.",
    url: "https://learnsql.com/blog/sql-basics-cheat-sheet",
    free_url: "https://learnsql.com/blog/sql-basics-cheat-sheet",
    is_free: true,
    difficulty: "beginner",
    paths: ["Backend Developer", "Full Stack Developer", "AI & ML"],
    layer_ids: [],
    topics: ["sql", "databases", "queries", "joins", "aggregation"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Regex Cheatsheet",
    author: "devhints.io",
    description:
      "Regular expression quick reference — character classes, anchors, quantifiers, groups, lookaheads, lookbehinds, and common real-world patterns for email, URL, and date validation.",
    url: "https://devhints.io/regexp",
    free_url: "https://devhints.io/regexp",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Backend Developer", "Frontend Developer", "Full Stack Developer", "QA Engineer"],
    layer_ids: [],
    topics: ["regex", "string-manipulation", "validation", "patterns"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "React Hooks Cheatsheet",
    author: "ohansemmanuel.com",
    description:
      "All React hooks at a glance — useState, useEffect, useContext, useReducer, useRef, useMemo, useCallback, useLayoutEffect, and custom hook patterns.",
    url: "https://react-hooks-cheatsheet.com",
    free_url: "https://react-hooks-cheatsheet.com",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["react", "hooks", "state-management", "components", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Docker CLI Cheatsheet",
    author: "devhints.io",
    description:
      "Every Docker command you need — build, run, exec, ps, logs, inspect, network, volume, compose up/down, and common Dockerfile instructions.",
    url: "https://devhints.io/docker",
    free_url: "https://devhints.io/docker",
    is_free: true,
    difficulty: "beginner",
    paths: ["DevOps", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["docker", "containers", "cli", "devops", "deployment"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Python Cheatsheet",
    author: "gto76 (GitHub)",
    description:
      "Comprehensive Python reference — built-in types, list/dict comprehensions, generators, decorators, context managers, classes, and the standard library essentials.",
    url: "https://github.com/gto76/python-cheatsheet",
    free_url: "https://github.com/gto76/python-cheatsheet",
    is_free: true,
    difficulty: "beginner",
    paths: ["AI & ML", "Backend Developer"],
    layer_ids: [],
    topics: ["python", "fundamentals", "data-structures", "oop", "standard-library"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "Linux Command Line Cheatsheet",
    author: "cheatography.com",
    description:
      "Essential Linux/Unix commands — file system navigation, permissions, processes, grep/sed/awk, pipes, cron, SSH, and shell scripting basics.",
    url: "https://cheatography.com/davechild/cheat-sheets/linux-command-line",
    free_url: "https://cheatography.com/davechild/cheat-sheets/linux-command-line",
    is_free: true,
    difficulty: "beginner",
    paths: ["DevOps", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["linux", "cli", "bash", "shell", "devops", "sysadmin"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "TypeScript Cheatsheet",
    author: "typescriptlang.org",
    description:
      "TypeScript at a glance — primitive types, arrays, tuples, enums, interfaces, type aliases, generics, union/intersection types, and utility types (Partial, Pick, Omit).",
    url: "https://www.typescriptlang.org/cheatsheets",
    free_url: "https://www.typescriptlang.org/cheatsheets",
    is_free: true,
    difficulty: "intermediate",
    paths: ["Frontend Developer", "Backend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["typescript", "types", "generics", "interfaces", "javascript"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    type: "cheatsheet",
    title: "CSS Selectors Cheatsheet",
    author: "devhints.io",
    description:
      "Every CSS selector in one place — element, class, ID, attribute, pseudo-class (:hover, :nth-child, :not), pseudo-elements, combinators, and specificity rules.",
    url: "https://devhints.io/css",
    free_url: "https://devhints.io/css",
    is_free: true,
    difficulty: "beginner",
    paths: ["Frontend Developer", "Full Stack Developer"],
    layer_ids: [],
    topics: ["css", "selectors", "specificity", "pseudo-classes", "layout"],
    agent_citation_count: 0,
    read_completion_rate: 0,
    exam_correlation: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seed() {
  const db = await connectDB();
  const col = db.collection("libraryResources");

  await col.createIndex(
    { title: "text", description: "text", topics: "text" },
    { name: "library_text_search", background: true }
  );

  await col.deleteMany({});
  console.log("Cleared existing library resources.");

  const result = await col.insertMany(resources);
  console.log(`Seeded ${result.insertedCount} library resources into 'libraryResources' collection.`);

  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
