/**
 * Which repository files the AI reviewer sees, within a character budget.
 * Pure — the tree comes in, an ordered selection comes out.
 *
 * The budget is small (free Groq tiers allow roughly 16k characters of code per
 * review), so it is spent on CODE first. Order of spending:
 *   1. a short slice of the README and the manifests (package.json …),
 *   2. source code, biggest first,
 *   3. tests — with room reserved up front so large source files cannot
 *      squeeze them out,
 *   4. ops files (Dockerfile, compose, CI — their existence is checked
 *      automatically), other docs, then noise (.gitignore, linter config…),
 *      only with whatever room is left.
 * A file that does not fit whole is still shown partially when enough room is
 * left, rather than hidden. The selection is deterministic for a given tree.
 */

import {
  REVIEW_FILE_CAPS,
  REVIEW_MAX_FILES,
  REVIEW_MIN_PARTIAL_CHARS,
  REVIEW_SKIP_FILE_BYTES,
  REVIEW_TEST_RESERVE,
} from "./constants.js";

const SKIP_DIRS = new Set([
  "node_modules", "dist", "build", "out", "coverage", ".git", "vendor", ".next", ".nuxt",
  ".cache", "tmp", ".turbo", ".vercel", "__pycache__", ".venv", "venv",
  // build output of Rust/Java/Gradle/CMake projects
  "target", ".gradle", ".idea", "cmake-build-debug", "cmake-build-release",
  // generated by Hardhat / Foundry / TypeChain
  "artifacts", "cache", "typechain-types",
  // mobile: Flutter, CocoaPods, Xcode, Expo, SwiftPM, .NET build output
  ".dart_tool", "Pods", "DerivedData", ".expo", ".build", ".symlinks", "obj",
]);
const SKIP_FILES = new Set([
  "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb", "npm-shrinkwrap.json",
  "pubspec.lock", "podfile.lock", "package.resolved",
]);
const TEXT_EXTENSIONS = new Set([
  "js", "jsx", "mjs", "cjs", "ts", "tsx", "json", "md", "yml", "yaml", "sql", "prisma",
  "sh", "toml", "graphql", "gql", "env", "example", "py", "go", "rs", "java", "rb", "txt",
  // C/C++, Kotlin, protobuf, Gradle — the systems, gRPC and JVM capstones
  "c", "h", "cc", "cpp", "hpp", "kt", "kts", "proto", "gradle",
  // smart contracts — Solidity, Vyper, Move
  "sol", "vy", "move",
  // mobile — Dart (Flutter), Swift (iOS), C# and XAML (.NET MAUI)
  "dart", "swift", "cs", "xaml", "csproj",
]);
const TEXT_BASENAMES = new Set([
  "dockerfile", "makefile", "procfile", ".env.example", ".dockerignore", ".gitignore",
  "pom.xml", "cmakelists.txt", "go.mod", "androidmanifest.xml",
]);

const basename = (path) => path.slice(path.lastIndexOf("/") + 1);
const extension = (path) => {
  const name = basename(path);
  const dot = name.lastIndexOf(".");
  return dot > 0 ? name.slice(dot + 1).toLowerCase() : "";
};

export const isReviewable = ({ path, size }) => {
  if (size > REVIEW_SKIP_FILE_BYTES) return false;
  const parts = path.split("/");
  if (parts.slice(0, -1).some((dir) => SKIP_DIRS.has(dir))) return false;
  const name = basename(path).toLowerCase();
  if (SKIP_FILES.has(name) || name.endsWith(".min.js") || name.endsWith(".map")) return false;
  return TEXT_BASENAMES.has(name) || TEXT_EXTENSIONS.has(extension(path));
};

// Go and Dart tests are *_test.go / *_test.dart; Java and Kotlin ones live under
// src/test/; Swift and C# ones are NoteTests.swift / NoteTests.cs.
const TEST_FILE = /(^|\/)(tests?|__tests__|spec)\/|\.(test|spec)\.[a-z]+$|_test\.(go|dart)$|Tests?\.(swift|kt|cs)$/i;
const DOC_FILE = /^readme\.md$/i;
// Project manifests tell the reviewer what the project is and what it depends on.
const MANIFEST_FILE =
  /^(package\.json|go\.mod|cargo\.toml|pom\.xml|build\.gradle(\.kts)?|cmakelists\.txt|makefile|pyproject\.toml|requirements\.txt|buf\.ya?ml|foundry\.toml|hardhat\.config\.(js|ts|cjs|mjs)|anchor\.toml|move\.toml|pubspec\.yaml|package\.swift|app\.json|app\.config\.(js|ts)|androidmanifest\.xml|capacitor\.config\.(ts|json)|ionic\.config\.json)$/i;
// Whether these exist is checked automatically; the reviewer only needs a glance at their content.
const OPS_FILE = /^(dockerfile|(docker-)?compose\.ya?ml|\.env\.example|\.github\/workflows\/[^/]+\.ya?ml)$/i;
// Almost no signal about the code: shown last, and only if room is left over.
const NOISE_FILE =
  /(^|\/)(\.gitignore|\.dockerignore|\.editorconfig|\.nvmrc|license(\.md|\.txt)?|eslint\.config\.[cm]?js|\.eslintrc(\.[a-z]+)?|\.prettierrc(\.[a-z]+)?|prettier\.config\.[cm]?js|tsconfig(\.[a-z]+)?\.json)$/i;
const SOURCE_EXT = new Set([
  "js", "jsx", "mjs", "cjs", "ts", "tsx", "sql", "prisma", "py", "go", "rs", "java", "rb", "graphql", "gql",
  "c", "h", "cc", "cpp", "hpp", "kt", "proto", "sol", "vy", "move", "dart", "swift", "cs", "xaml",
]);

/** doc | manifest | ops | noise | test | source | other */
export const kindOf = (path) => {
  if (DOC_FILE.test(path)) return "doc";
  if (MANIFEST_FILE.test(path)) return "manifest";
  if (OPS_FILE.test(path)) return "ops";
  if (NOISE_FILE.test(path)) return "noise";
  if (TEST_FILE.test(path)) return "test";
  if (SOURCE_EXT.has(extension(path))) return "source";
  return "other";
};

const PRIORITY = { doc: 0, manifest: 0, ops: 0, source: 1, test: 2, other: 3, noise: 4 };
export const priorityOf = (path) => PRIORITY[kindOf(path)];

const byPath = (a, b) => a.path.localeCompare(b.path);
// Bigger files first: they are usually the core of the project (routes,
// services), and a hard cap per file keeps one giant file from starving the rest.
const bySizeDesc = (a, b) => b.size - a.size || byPath(a, b);
const byDepth = (a, b) => a.depth - b.depth || byPath(a, b);

/**
 * Spend up to `budget` characters on `candidates`, in order, adding what fits
 * to `state.selected`. Returns what is left of the budget.
 */
const fillBudget = (candidates, budget, state) => {
  let left = budget;
  for (const f of candidates) {
    if (state.selected.length >= REVIEW_MAX_FILES) break;
    const cap = REVIEW_FILE_CAPS[f.kind];
    const want = Math.min(f.size, cap);
    if (want <= left) {
      state.selected.push({ path: f.path, size: f.size, cap });
      state.picked.add(f.path);
      left -= want;
    } else if (left >= REVIEW_MIN_PARTIAL_CHARS) {
      state.selected.push({ path: f.path, size: f.size, cap: left }); // shown partially
      state.picked.add(f.path);
      left = 0;
    }
  }
  return left;
};

/**
 * @param {{path:string, size:number}[]} entries  blob entries from the tree
 * @param {number} maxChars  total budget across all selected files
 * @returns {{ selected: {path:string, size:number, cap:number}[], omitted: string[], rest: object[] }}
 *   `cap` is how many characters of that file to show (the whole file unless it is partial).
 *   `rest` is every file NOT selected, in the order it would have been chosen —
 *   pass it to topUpReviewFiles once the real cost of the selection is known.
 */
export const selectReviewFiles = (entries, maxChars) => {
  const files = entries
    .filter(isReviewable)
    .map((e) => ({ ...e, kind: kindOf(e.path), depth: e.path.split("/").length }));
  const of = (...kinds) => files.filter((f) => kinds.includes(f.kind));

  const state = { selected: [], picked: new Set() };
  const stages = {
    docs: [...of("doc").sort(byPath), ...of("manifest").sort(byPath)],
    source: of("source").sort(bySizeDesc),
    tests: of("test").sort(bySizeDesc),
    // Dockerfile, compose, CI, .env.example: their EXISTENCE is checked automatically,
    // so they only get what is left after the code and the tests.
    ops: of("ops").sort(byPath),
    other: of("other").sort(byDepth),
    noise: of("noise").sort(byPath),
  };

  let left = fillBudget(stages.docs, Math.max(0, maxChars), state);

  const { fraction, min, max } = REVIEW_TEST_RESERVE;
  const reserve = stages.tests.length ? Math.min(left, Math.min(max, Math.max(min, Math.floor(left * fraction)))) : 0;

  const afterSource = fillBudget(stages.source, left - reserve, state);
  left = fillBudget(stages.tests, reserve + afterSource, state);
  left = fillBudget(stages.ops, left, state);
  left = fillBudget(stages.other, left, state);
  fillBudget(stages.noise, left, state);

  const rest = Object.values(stages).flat().filter((f) => !state.picked.has(f.path));
  return { selected: state.selected, omitted: rest.map((f) => f.path), rest };
};

/**
 * Second pass. Selection works from RAW file sizes, but the reviewer is shown
 * the compact view (no blank or comment-only lines), which is noticeably
 * smaller. After downloading, the caller measures the real cost and gives the
 * unspent budget back here to be spent on the next-best files.
 *
 * @param {object[]} rest  `rest` from selectReviewFiles
 * @param {number} budget  characters still unspent
 * @returns {{ selected: {path:string, size:number, cap:number}[], omitted: string[] }}
 */
export const topUpReviewFiles = (rest, budget) => {
  const state = { selected: [], picked: new Set() };
  fillBudget(rest, Math.max(0, budget), state);
  return { selected: state.selected, omitted: rest.filter((f) => !state.picked.has(f.path)).map((f) => f.path) };
};
