import { useEffect, useState } from "react";

// Module-level cache: survives re-renders and remounts, so going back to a
// track is instant. Tracks are static per deploy, so it never needs clearing.
const cache = new Map();

const IDLE = { key: null, layers: null, loading: false, error: null };

/**
 * Loads the layers of one roadmap track from /roadmaps/<category>/<track>.json
 * (generated by scripts/splitRoadmaps.js).
 *
 * State is tagged with the key it belongs to. Without that, the render right
 * after a track switch would still return the previous track's layers.
 */
export function useTrackLayers(categoryId, trackId) {
  const key = categoryId && trackId ? `${categoryId}/${trackId}` : null;
  const [state, setState] = useState(IDLE);

  useEffect(() => {
    if (!key || cache.has(key)) return;

    // Aborting on cleanup means a slow, outdated request can never
    // overwrite the track the user switched to.
    const ctrl = new AbortController();
    setState({ key, layers: null, loading: true, error: null });

    fetch(`/roadmaps/${key}.json`, { signal: ctrl.signal })
      .then((res) => {
        // No file means the track isn't authored yet: resolve to null so the
        // page shows "being authored", not an error. The SPA rewrite in
        // vercel.json answers a missing file with index.html and a 200, so
        // a non-JSON response counts as missing too.
        const isJson = res.headers.get("content-type")?.includes("json");
        if (res.status === 404 || (res.ok && !isJson)) return null;
        if (!res.ok) throw new Error(`Failed to load track ${key}: ${res.status}`);
        return res.json();
      })
      .then((layers) => {
        cache.set(key, layers);
        setState({ key, layers, loading: false, error: null });
      })
      .catch((error) => {
        if (error.name !== "AbortError") setState({ key, layers: null, loading: false, error });
      });

    return () => ctrl.abort();
  }, [key]);

  if (!key) return IDLE;
  if (cache.has(key)) return { key, layers: cache.get(key), loading: false, error: null };
  // Effect hasn't run yet for a new key: report loading, never the old track.
  return state.key === key ? state : { key, layers: null, loading: true, error: null };
}
